### ISSUE TITLE
Công Ty Cổ Phần Ntq Solution tuyển ruby-developer tại Hà Nội 

### ISSUE THREAD

**Issue by huydx** [ruby-vietnam/job_board#10]
### Mô Tả Công Việc

- Tham gia phát triển các dự án cho khách hàng Nhật/Nga/Úc;
- Làm việc ở nước ngoài tuỳ vào yêu cầu của từng dự án (Ưu tiên người biết tiếng Nhật)
- Báo cáo hàng ngày, hàng tuần cho cấp trên và team member trong dự án
- Đóng góp vào việc xây dựng phát triển công ty

* QUYỀN LỢI
- Làm việc cùng với những người có 8-10 năm kinh nghiệm trong lĩnh vực software, ở vị trí Software Architect của những hệ thống lớn
- Được định hướng phát triển chuyên sâu về công nghệ
- Có cơ hội làm những việc thách thức, phát huy hết khả năng bản thân

- Mức lương: $400-$1200/tháng + Thưởng Tết;
- Xét TĂNG LƯƠNG một năm 2 lần (tháng 6 và tháng 12); 
- PHỤ CẤP: Tiếng Nhật hàng tháng (Nếu có bằng tiếng Nhật): N3: 1 triệu đồng ; N2: 2 đến 3 triệu đồng , N1: 5 triệu đồng; 
- Đóng bảo hiểm y tế, bảo hiểm xã hội theo quy định của Nhà nước.
- MÔI TRƯỜNG LÀM VIỆC: thân thiện, năng động, có cơ hội thăng tiến.
- Được hưởng các CHẾ ĐỘ PHÚC LỢI của công ty: thưởng lễ Tết, nghỉ mát hàng năm, thể thao, TeamBuilding, các lớp học nâng cao trình độ ngoại ngữ (tiếng Anh, tiếng Nhật)…
- Khám sức khỏe 1 năm/1 lần.
Yêu Cầu Công Việc
- Tốt nghiệp Đại học chuyên ngành CNTT hoặc có kiến thức tương đương.
- Nắm vững về OOP. Có suy nghĩ về việc tối ưu và refactoring khi viết code
- Có hiểu biết về Design Pattern, ORM, RESTful, TDD, ...
- Có kinh nghiệm làm việc với MySQL hoặc NoSQL (MongoDB, ...)
- Thành thạo các công cụ quản lý mã nguồn: GIT, SVN. 
- Có thể đảm bảo deadline cũng như chất lượng sản phẩm. 
- Tư duy tốt, chủ động trong công việc, có tinh thần trách nhiệm cao để hoàn thành công việc được giao.
- Có khả năng đọc hiểu tài liệu tiếng Anh. Có ý thức trong việc tự tìm hiểu và nâng cao năng lực bản thân.

*** YÊU CẦU với vị trí lập trình Web (Ruby / PHP / dotNET / Java)
- Nắm vững ít nhất 1 MVC framework, như là: Ruby on Rails; CakePHP, Laravel (PHP); Spring MVC (Java), MVC .NET
- Thao tác tốt với HTML, CSS, JavaScript (jQuery, Ajax, ...), Bootstrap, JSON, XML, ...
- Hiểu biết sâu về lập trình web: Cookies, Cơ chế quản lý Sessions, HTTP Requests, Caching,...

*** ƯU TIÊN ứng viên có thêm các kinh nghiệm sau:
- Có thể làm việc trên môi trường Linux/Ubuntu 
- Có kinh nghiệm làm việc với cho các đối tác nước ngoài
- Đọc được tài liệu tiếng Nhật là 1 lợi thế.

*** TRAINING FRESHER
Với các ứng viên chưa có nhiều kinh nghiệm làm việc, hoặc đang học các năm cuối ở trường ĐH, công ty sẵn sàng tạo điều kiện hướng dẫn đào tạo từ đầu. 

Yêu cầu:
- Thực sự đam mê với việc lập trình
- Không ngại khó khăn, thử thách để học hỏi

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
