### ISSUE TITLE
Ha Noi - Ruby on Rails Developer

### ISSUE THREAD

**Issue by Vnextsoftware** [ruby-vietnam/job_board#102]
# VNEXT SOFTWARE
Address: VNext Software Building (56 Luu Huu Phuoc, Cau Dien, Nam Tu Liem, Ha Noi, Viet Nam)
Website: http://www.vnext.vn/vn
FB: https://www.facebook.com/tuyendungvnextsoftware

## THE JOB
VNext is looking for 02  Ruby on rail developers that are writing short code in a specific and structured way. You will be playing a key role in the tech team.

## REQUIREMENTS
- 1 year of experience Ruby/Rails 
- Competently with Github and framework rails
- Good knowledge in JS, HTML,CSS

## CONTACT: Ms Hang
- Email: hr@vnext.vn
- Skype: hangpham308

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
