### ISSUE TITLE
Wonolo - Startup Company

### ISSUE THREAD

**Issue by dinhthi1610** [ruby-vietnam/job_board#103]
Loại công việc:	Toàn thời gian cố định
Số lượng cần tuyển:	5
Thời gian nộp hồ sơ:	15/10/2015
Nơi làm việc: 		Hồ Chí Minh
Lương : 		800$-1200$ (tùy năng lực)
## Nhiệm vụ:
- Lập trình backend dùng ruby on rails

### Yêu cầu chung
- Tiếng Anh tốt, đặc biệt về khả năng đọc hiểu thành thạo
- Khả năng nắm bắt, học hỏi kỹ thuật mới nhanh
- Có khả năng làm việc tự chủ và làm việc theo nhóm
- Tinh thần làm việc tốt, có trách nhiệm, thái độ cầu tiến trong công việc

### Yêu cầu về lập trình ruby on rails
- Ít nhất 2 năm kinh nghiệm làm các dự án dùng Ruby on Rails
- Ưu tiên các ứng viên có thêm một trong các kinh nghiệm sau:
  + Có kinh nghiệm về Javascript, CSS3, HTML5, XML, XSLT, JSON
  + Có kinh nghiệm về MySQL, MongoDB, PostgreSQL
  + Có kinh nghiệm về Linux server administration, shell script 
  + Có kinh nghiệm về config web server trên Linux

## Quyền lợi:
 - Thu nhập thỏa thuận tùy theo năng lực của ứng viên, cạnh tranh
- Bảo hiểm Y tế, xã hội, Bảo hiểm wonolo care hàng trăm triệu mỗi năm
- Các chương trình lễ hội, văn hóa, du lịch của công ty
- Khóa học anh văn nâng cao

Liên hệ : todinhthi@gmail.com
skype : dinhthi1610

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
