### ISSUE TITLE
Autonomous - Fullstack ruby/python web developer - [Fulltime Saigon, Viet Nam]

### ISSUE THREAD

**Issue by gkmbinh** [ruby-vietnam/job_board#105]
Autonomous
the company’s mission is to build a platform for an autonomous robot with plenty of sensors, advanced computer vision and a good dose of artificial intelligence built-in so it can’t just react to what you’re telling it to do, but also proactively alert you and handle tasks quietly in the background.

Requirements

Python(Flask) , or PHP, or Ruby. -> but you will work with Python 
Linux arm board.
AWS 
SQL
Jquery,
Bootstrap

Offer: 
Macbook Pro, phone Nexus 5 , Bao Viet Healthy care, ...  
Salary : 800-1500 USD

Contact 
Please contact me by email gkmbinh@gmail.com or binh@robotbase.com

OFFICE : Tan Binh dist, Ho Chi Minh city, VN. 
Thank you

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
