### ISSUE TITLE
[HN] Looking for Ruby On Rails (Urgent!!!...)

### ISSUE THREAD

**Issue by nguyenhao105** [ruby-vietnam/job_board#107]
Tuyển Lập trình viên Ruby On Rails ( Salary up to 1000$)

MÔ TẢ CÔNG VIỆC:
Xây dựng các ứng dụng web, webservice
Tham gia vào thiết kế và review source code
Báo cáo tiến độ và tình trạng công việc trực tiếp tới quản lý dự án
Tiếp cận và được đào tạo theo mô hình phát triển dự án Agile, Scrum

YÊU CẦU:
- Có > 1 năm kinh nghiệm làm việc với Framework Ruby on Rails hoặc các framework khác sử dụng ngôn ngữ Ruby
- Thao tác tốt với HTML, CSS, JavaScript (Jquery, Ajax, ...), Bootstrap, JSON, XML, ...
- Thành thạo các công cụ quản lý mã nguồn: GIT, SVN.
- Có thể đảm bảo deadline cũng như chất lượng sản phẩm.
- Có khả năng làm việc tốt trong môi trường Teamwork cũng như làm việc độc lập.
- Khả năng tư duy tốt, chủ động trong công việc, có tinh thần trách nhiệm cao để hoàn thành công việc được giao

QUYỀN LỢI:
- Cơ hội đi Nhật ngắn hàn và dài hạn: Công ty mẹ G-Next và chi nhánh V-Next Japan tại Tokyo
- Môi trường làm việc thoáng mát, sạch sẽ, có nhiều không gian vui chơi, thư giãn 
- TRANG THIẾT BỊ: Mới, đẹp, hiện đại
- Phong cách làm việc chuyên nghiệp, tất cả đều hệ thống thành quy trình và tài liệu rõ ràng
- Nâng cao kỹ năng, giá trị khi làm việc với khách hàng chuyên nghiệp, khó tính bậc nhất thế giới 
- Học tập và thăng tiến với QUỸ ĐÀO TẠO KHÔNG GIỚI HẠN, các lớp học tiếng Nhật và tiếng Anh được tổ chức
- Thưởng khi bạn vượt qua các kỳ thi chuyên môn kỹ năng (Bằng cấp/chứng chỉ bạn vẫn giữ)
- ĐIỀU CHỈNH LƯƠNG 2 lần/năm để những cố gắng của bạn được đền đáp
- KHÁM SỨC KHỎE định kỳ hàng năm, với các gói khám theo nhu cầu cá nhân
- THƯỞNG DỰ ÁN: Kết thúc Quý đánh giá và trao thưởng tiền mặt
- GIẢI TRÍ: Game AOE, Pi -a, phượt, ăn uống đình đám mỗi tháng một lần, đặc biệt là đội bóng đá hoạt động sôi nổi.

HỒ SƠ YÊU CẦU:
- Bản CV: Ghi rõ thông tin cá nhân, tóm tắt quá trình học tập, kinh nghiệm làm việc.
- Subject ghi rõ vị trí tuyển dụng “Lập trình viên Ruby”.
- Email: hr@vnext.vn

Thông tin công ty:
Công ty Cổ phần VNext Software
Địa chỉ: 56 Lưu Hữu Phước - Mỹ Đình I - Nam Từ Liêm - Hà Nội

Mọi thắc mắc xin liên hệ qua email hoặc Skype: nguyenhaohr.ulsa
Rất mong nhận được sự quan tâm từ bạn ^^!

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
