### ISSUE TITLE
Mortgage Club - Full Stack Web Developer

### ISSUE THREAD

**Issue by geenguyen** [ruby-vietnam/job_board#108]
**Do you want to help disrupt the 8 trillion dollar mortgage industry in the United States?**
Mortgage Club is an early based stage fintech startup in San Francisco. It was founded by 2 UC Berkeley classmates who have an engineering background and experiences working for Wall Street hedge funds and Silicon Valley tech companies for nearly a decade.
We leverage data and technology to revolutionize the 8 trillion dollar mortgage industry by making it cheaper, faster, and more transparent. We aim to be Uber of the mortgage industry by providing a real-time mortgage marketplace where homebuyers can easily apply, shop, and lock in the best loan in minutes.  

**Location**
Work at Mortgage Club’s Saigon Hacker House at Saigon Pearl, Ho Chi Minh City.
You can stay there for free if you’d like. Central location, less than 10 minutes away from cool hangout spots in the city like Bitexco Financial Tower, Vincom Shopping Mall, AB Tower etc.

**Our team**
- Mortgage Club has an engineering-led culture. We look for entrepreneurial engineers who see the total picture and can put on lots of hats at once. Our engineering team in Saigon employs Scrum methodology and achieve a Joel score of 10 out of 12. 
- We move fast, deploy code every day, and are not afraid to break things. We work hard but have a lot of fun in the process. 
- We’re also a big fan of side projects and hackathons. Our team member recently won the first prize of the East Agile Hackathon.
- We’re currently looking for 2 full stack web developers with great technical ability, a get-shit-done attitude, and willingness to learn new stuff to join our team.

**Responsibilities**
- You’ll help build an Uber-like infrastructure that can turn an extremely complicated mortgage process into something as simple as booking a flight or hotel.
- Our back-end stack is in Ruby on Rails riding on AWS and Postgres RDS. Using RSpec and Cucumber we believe in just enough testing to provide full coverage without introducing a lot of change friction. Our architecture is lightweight and modular in nature adhering to the fat models, skinny controllers ideology.
- In the front-end, we serve a few isomorphic single-page apps using ReactJS for the views, organize the data flow with Flux architecture, and test our application with Jest. We use a hybrid version of Bootstrap styles mixed with hand-built Sass components as our CSS library.

**Your Skills and Experience**
Requirements:

- 1-5 years of experience in object oriented design, development and implementation using Ruby on Rails
- Experience with ReactJS (or another Javascript framework)
- Hands-on experience writing automated tests using RSpec, Cucumber
- Knowledge in image processing is a plus
- Comfortable with reading and writing in English

Must have:

Be a normal human being (We’re a big fan of work hard play hard culture so expect to have happy hours, team outings, travel several times a year)
 
**Why you’ll love working here**

- Competitive salary (depends on your talent, not experience)
- Potential salary increase of 20-50% after 1 year
- Stock options for outstanding team members
- Your choice of Macbook Pro or Macbook Air (sorry no Windows)
- Free lunch everyday (we always get headache deciding what and where to eat so let’s just do catered lunch)
- Free gym membership (getting fit is good for both your physical appearance and career) 
- Free laundry (you think washing and folding clothes is a good use of your time?)
- Relaxing and flexible working environment
- Opportunity to travel to San Francisco to work with the team 

If interested, please send us your resume and a cool program that you’ve written in Rails. Contact me today! gee@mortgageclub.io

**Joel Test score: 10 out of 12**
The [Joel Test](http://www.joelonsoftware.com/articles/fog0000000043.html) is a twelve-question measure of the quality of a software team.
:+1: Do you use source control?
:+1: Can you make a build in one step?
:+1: Do you make daily builds?
:+1: Do you have a bug database?
:+1: Do you fix bugs before writing new code?
:+1: Do you have an up-to-date schedule?
:+1: Do you have a spec?
:+1: Do programmers have quiet working conditions?
:+1: Do you use the best tools money can buy?
:construction_worker:  Do you have testers?  *but we write tests with RSpec + Cucumber*
:+1: Do new candidates write code during their interview? 
:construction_worker: Do you do hallway usability testing?

![download](https://cloud.githubusercontent.com/assets/14802786/10300702/3afe1da0-6c24-11e5-836e-042de8c56fd5.png)

**Comment by billytran1222** [comment]
:+1:

**Comment by leovinh** [comment]
(y)

**Comment by joneslee85** [comment]
:+1: I really love the details you put into this job description, I wish every other recruiters would treat their potential devs like million dollar superstar and do their best to make their company standing out.

**Comment by rebyn** [comment]
> Our team member recently won the first prize of the East Agile Hackathon.

:bouquet: @vumanhcuongit.

**Comment by billytran1222** [comment]
@rebyn My goal is to turn "team member" into "team members" :smile:

**Comment by billytran1222** [comment]
@joneslee85: Developers are million dollar superstars indeed :smile:

**Comment by gkmbinh** [comment]
![image](https://cloud.githubusercontent.com/assets/1903350/10329460/0990772c-6cec-11e5-8bff-61d452129e61.png)

**Comment by rhacker** [comment]
@gkmbinh hi anh Binh :D

**Comment by gkmbinh** [comment]
@rhacker  gi the e? :D 
team a dang tuyen full-stack web ne. e biet ai hok ? :D
