### ISSUE TITLE
[HN] Urgent Ruby on Rails Senior/Leader $900 - $1500

### ISSUE THREAD

**Issue by moha114** [ruby-vietnam/job_board#109]
# JOB DESCRIPTION	
1. Guide the team to the success

- Deeply understand the product and it's value 
- Analyze system requirement, play a key role in system architecture 
- Decide technical direction 
- Resolve any technical issue together with seniors 
- Train, encourage and facilitate team and lead team members to their optimum performance levels and career development 
- Responsible for launching and maintenance 
- Resolve conflicts between members 
- Protect team from overload 
- Write technical supporting documentation

2. Responsible for the progress and the quality of the project.

- Make clear goal and deadline of the team 
- Actively work with QA to insure timely releases 
- Start discussion with team or BOM when problem found 
- Delegate. You are the last person who code.

YOUR SKILLS AND EXPERIENCE	
- Bachelor’s Degree (Computer Science or related) 
- Excellent communication in English is a plus 
- At least 5 to 7 years as a Web developer with 3+ years in leader role 
- Experienced with Web programing languages (Ruby and rails is an advantage) 
- Experienced with Single Page Application (SPA), have a good skills and knowledge with MVC JavaScript frameworks like: Backbones, Angular JS or Mithril (Mithril is an advantage), AJAX, Websockets, Data transport (XML, JSON, AJAX), server architectures 
- Experienced in Search engine optimization, Client/Server code partitioning 
- Strong in SQL writing and should have worked with leading Databases: MySQL. 
- Strong trouble-shooting and problem-solving skills with a logical and pragmatic attitude 
- Team player with strong oral and interpersonal skills

WHY YOU'LL LOVE WORKING HERE	
1. Intensive training on Ruby on Rails 
Ruby on Rails is “most well thought-out web development framework” optimized 
for programmer happiness and sustainable productivity. One of the most popular 
framework for start-ups in the world.

- We will train you from the very basic of Ruby on Rails 
- First 2 weeks for basic knowledge. Next 2 weeks for building a sample project.

*Mentoring Program for New-comers (1-1) 
An uniquely - designed program for new comers is provided right after your joining with us. You will be trained and guided closely by 1 senior and experienced staff about everything from Tech to other skills. Also, you have a lot of chance to get feedback from Japanese experts daily.

2. Daily review by Japanese experts 
We use GitHub like system internally and you upload your code there. Every day 
Japanese experts will review and feedback about your code how to improve. Also 
engineers each other can see the code and share the opinions. 
You can develop your skill every day here.

3. Not only tech but also working mindset 
Besides the technical skill development, we have learning program for 
-Professionalism: Sincerity, Punctuality, etc. 
-How to make full use of your brain: Logical thinking, Analyzing, 
Hypothesis testing, Problem solving, Presentation with logic. 
- Project management: Goal sharing, Planning, Tracing the 
process, Archiving the goal. 
- Communications: Leadership, Couching, Concern for others 
& proper self-recognitions.

4. We are a start-up 
Our Vietnam office started from July this year. We are a start-up team and there 
are many chances for you to cover many areas. Start-up is always a good 
environment to be a full-stack developer.

5. Working environment & Benefits 
Expense - free for your learning English/Japanese 
A creative and high-tech working environment with various tools of 
communication (ChatWork, Jira, Confluence,Google hangout, Skype,…) 
-Chance to be trained in Japan office for the cream of the crop 
Lunch & parking fee allowance 
Salary review after every 6 months & 13th month salary bonus

* There are training programs to Japan for the cream of the crop. 
Enjoy high chance of promotion – high possibility to become the Key person of the company. 
* Other activities: annual travelling with the company, teambuilding, birthday party,… 
* Working time: 5 days/week, from 08:00 am to 17:00 pm. Have every-other-week Saturday off (Basically Saturdays will be spent for intense-training, study group and personal projects for skill-up). Sundays and other public holidays are off as prescribed by the State regulations. 
* Flexible work time, required to adjust the work time according to the progress of tasks to respect the projects deadlines.

D. OTHER DETAILS 
* CV in English 
* Candidates are going to do a test before interviewing. 
* 2 interview rounds.

E. HOW TO APPLY
* Sending CV (In English) to hr@mmj.vn 
For further information please contact 
Ms.Mai ( 0466873572)
Skype: maido_th411

*Company information
Media Max Japan (Vietnam)
Address: 17th Floor, HL Building, 82 Alley, Cau Giay, Hanoi.
http://mmj.vn/

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
