### ISSUE TITLE
Front-end engineer - TPHCM

### ISSUE THREAD

**Issue by JAC-Huyen** [ruby-vietnam/job_board#11]
Em tuyển một anh front-end engineer, với những điều kiện dưới đây.
Lương tầm around 1000 usd nha các anh
・know how to improve quality of source code and system
・Javascript, AngularJS
・coffeescript, sass, nodejs, gulp
・good at system design
・good at Ruby is a plus

Thông tin công ty
・Công ty Nhật làm ở quận 3
・Môi trường pro, công ty hơi bị đẹp nha.
・Thời gian làm việc: 8:30 ~ 17:30 từ T2~T6

Chi tiết các anh gửi CV cho em Huyen.Pham@jac-recruitment.com
Hoặc gọi em 0916.092.848

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
