### ISSUE TITLE
Sugar Ventures - ROR backend - Full time - Ho Chi Minh City

### ISSUE THREAD

**Issue by pthaoasi** [ruby-vietnam/job_board#111]
### The Company:
SUGAR is a Singapore based early stage startup studio that nurtures greenfield ideas to change the world. Unlike traditional accelerators or incubators, it will unearth great startups from the idea stage, provide seed funding, help organic growth, and lead to a flourishing exit.

Be part of our innovative company, have great fun with us and be amongst talents where you can demonstrate your skills and take on challenges, be a standout from the crowd, be waiting no longer, apply RIGHT NOW!

### The Role:
We are looking for a Ruby on Rails developer with experience working with AWS, Ubuntu Linux and PostgreSQL. DevOps or frontend experience a big plus.

### Responsibilities:
You will need to be able to develop Ruby on Rails web applications and REST APIs from scratch, including setting up and maintaining the necessary infrastructure (AWS EC2, S3, RDS, IAM).
* Can develop and maintain Ruby on Rails application with supporting infrastructure
* Delivers projects on time, within budget and to required quality standards
* Works well with a team but can work independently when required
* Interprets requirements and yields solid design specification, within existing frameworks
* Implements efficient and effective solutions from design specifications
* Effectively tests developed software
* Architects/designs new solutions when required
* Can make design decisions that ensure future scalability while taking into account current budget
* Provides accurate estimates of the effort required to complete a task
*Produces and maintains high quality documentation
* Recommends and implements process improvements

### Requirement:
* 3-5 years of Ruby on Rails experience
* Experience working with Amazon Web Services
* Experience working with PostgreSQL or MySQL
* Experience working with Unix operating systems
* Ability to work independently and within a team
* Good communication skills
* Good problem solving skills
* Attention to details
* Knowledge of HTML, CSS, JavaScript, jQuery, Bootstrap a plus
* Knowledge of Capistrano, Chef, Puppet, Docker, Ansible a plus
* Degree in Computer Science or related field a plus

### Contact:
Send CV (English) to thao.nguyen@sugar.sg. For further information contact Ms.Thao +84908386438.
Company information: www.sugar.sg

**Comment by joneslee85** [comment]
@pthaoasi thanks for the submission, it'd be nicer if you use Markdown to format header and bullet-points, please also add company logo or pictures of your workplace.

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
