### ISSUE TITLE
Sugar Ventures - front end developer 

### ISSUE THREAD

**Issue by pthaoasi** [ruby-vietnam/job_board#112]
### The Company:
SUGAR is a Singapore based early stage startup studio that nurtures greenfield ideas to change the world. Unlike traditional accelerators or incubators, it will unearth great startups from the idea stage, provide seed funding, help organic growth, and lead to a flourishing exit.

Be part of our innovative company, have great fun with us and be amongst talents where you can demonstrate your skills and take on challenges, be a standout from the crowd, be waiting no longer, apply RIGHT NOW!

### The Role:

We are looking for a front-end web developer experienced working with JavaScript frameworks.

### Responsibilities

You will need to be able to implement Single-Page Applications using JavaScript frameworks and build web interface for Ruby on Rails projects.
* Can convert PSD design to HTML and CSS 
* Creates responsive web pages that work well on a wide range of devices
* Creates web pages conforming to HTML5 and CSS3 standards
* Delivers projects on time, within budget and to required quality standards
* Works well with a team but can work independently when required
* Implements efficient and effective solutions from design specifications
* Effectively tests developed software
* Provides accurate estimates of the effort required to complete a task
* Recommends and implements process improvements

### Requirements:

* 3 years of HTML/CSS/JavaScript experience
* Good practical knowledge of HTML5/CSS3/jQuery
* Familiarity with modern JavaScript frameworks - Ember.js and/or AngularJS
* Strong knowledge of standards-based web development and cross-platform compatibility
* Experience working with Ruby on Rails
* Experience working with REST APIs
* Good SEO knowledge
* Ability to work independently and within a team
* Good communication skills
* Good problem solving skills
* Attention to details
* Degree in Computer Science or related field a plus

### Contact:
Send CV (English) to thao.nguyen@sugar.sg. 
Company information: www.sugar.sg

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
