### ISSUE TITLE
Sugar Ventures - User Experience Designer - full time

### ISSUE THREAD

**Issue by pthaoasi** [ruby-vietnam/job_board#113]
### The Company:
SUGAR is a Singapore based early stage startup studio that nurtures greenfield ideas to change the world. Unlike traditional accelerators or incubators, it will unearth great startups from the idea stage, provide seed funding, help organic growth, and lead to a flourishing exit.

Be part of our innovative company, have great fun with us and be amongst talents where you can demonstrate your skills and take on challenges, be a standout from the crowd, be waiting no longer, apply RIGHT NOW!

### The Role:
Sugar is looking for a user experience designer who has a passion for creating exceptional user experiences.The ideal candidate will thrive in a work environment that requires strong problem solving skills and independent self-direction, coupled with an aptitude for team collaboration and open communication. This individual excels at providing both highly analytical as well as highly creative ideas to a design engagement. The candidate will also have extensive experience in a fast-paced and innovative development environment. A thorough understanding of contemporary user-centered design methodologies is a must.

### Responsibilities:
* Handle the UX design needs of projects you are assigned to
* Create, coordinate, lead, inspire and/or oversee all UX deliverables including: user research, competitive audits, experience roadmaps and usability testing
* Provide UX budgeting, scoping, and project definition creation
* Manage all aspects of UX design delivery end to end
* Articulate Sugar’s overall UX vision across the organisation
* Provide oversight to the enhancement of UX across the Company’s products
* Work with user interface designers/graphic designers to define effective design solutions that meet user expectations,are easy to use and create great product experiences
* Turn ideas into presentable concepts and help UI Designer to translate those concepts into design recommendations that achieve simplicity, despite the inherent complexity of processes being supported
* Work closely with Managers, people in technical and creative functions to achieve high-quality and consistent delivery

### Requirements :
* At least 4-5 years of experience in user experience design, demonstrable via portfolio of products and deliverables
* Preferred: Master’s degree in Interaction Design or Computer Science. Acceptable: Bachelor’s degree in relevant field (Interaction Design, Psychology, Human Factors, Anthropology, HCI, etc.)
* Demonstrated proficiency in making interactive and time-based products that look great, work great, and are a pleasure to use
* Strong conceptualization skills with deep attention to detail and the demonstrated ability to convey the intricacies of a desired experience to multiple audiences
* Intuitive understanding of and empathy for everyday users: their motivations, goals, and abilities
* Demonstrated ability to recast a problem in order to arrive at an elegant and innovative solution, then convey that solution tangibly
* Must be extremely detail-oriented, able to define ideas down to a specification level.
* Experience participating in user research and usability testing for individual projects.
* Demonstrable experience prototyping for conceptual development, testing, demonstration and documentation
* Ability to explain user experience to non-design personnel, in their language
* A good understanding of graphic design and the ability to use visual design techniques to convey information and instructions to improve usability
* Excellent verbal and interpersonal communication skills
* Must be self-motivated, client experience oriented and a strong team player

### Additional Requirements:
_ Passion for good experience – You know the difference between good and great and are able to work within a cross-functional team to deliver excellent experiences in out-of-box, setup, initial use, day-to-day-use, and troubleshooting
_ Rapid iteration – You're eager to try your early work on real people and use the feedback to make a better prototype on your way to an awesome final design
_ Team skills – You speak the languages of designers, business people, and users. You are collaborative, participatory, and inspire others to contribute
_ Professional skills – You have strong written, verbal, and presentation skills. You demonstrate care, vision, and planning in everything you do

### Contact:
Send CV (English) to thao.nguyen@sugar.sg
Company information: www.sugar.sg

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
