### ISSUE TITLE
Sugar Ventures - Mobile Developer (Android/iOS) [full time, Saigon]

### ISSUE THREAD

**Issue by pthaoasi** [ruby-vietnam/job_board#114]
### The Company:

SUGAR is a Singapore based early stage startup studio that nurtures greenfield ideas to change the world. Unlike traditional accelerators or incubators, it will unearth great startups from the idea stage, provide seed funding, help organic growth, and lead to a flourishing exit.

Be part of our innovative company, have great fun with us and be amongst talents where you can demonstrate your skills and take on challenges, be a standout from the crowd, be waiting no longer, apply RIGHT NOW!

### The Role:

With the fast growing and ambitious group of businesses, we are in search again for passionate and talented Mobile developers to build some exciting and phenomenal apps for the endless mobile users.
You need to bring with you Android or iOS mobile development experience. As we are moving extremely fast with the services we have to offer, you will need to be able to take on projects and run with them independently.

### Responsibilities:
* Strong understanding of iOS/Android SDK
* 2-3 years of working experience with maps, audio, databases, third party SDKs, web service communication, APIs and unit testing
* Strong understanding of Object Oriented Programming and design patterns
* Ability to design mobile applications that follow Apple/Google human interface guidelines
* Experience with server side programming (Ruby on Rails/Django/.NET) and cloud technologies (AWS/Google App Engine) is a plus
* Ability to work independently and within a team
* Good communication skills
* Good problem solving skills
* Attention to details
* Degree in Computer Science or related field a plus

### Contact:
Send CV (English) to thao.nguyen@sugar.sg
Company information: www.sugar.sg

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
