### ISSUE TITLE
SUGAR VENTURES - C++ Software Developer - Full time - Ho Chi Minh City

### ISSUE THREAD

**Issue by pthaoasi** [ruby-vietnam/job_board#115]
### The Company:

SUGAR is a Singapore based early stage startup studio that nurtures greenfield ideas to change the world. Unlike traditional accelerators or incubators, it will unearth great startups from the idea stage, provide seed funding, help organic growth, and lead to a flourishing exit.

Be part of our innovative company, have great fun with us and be amongst talents where you can demonstrate your skills and take on challenges, be a standout from the crowd, be waiting no longer, apply RIGHT NOW!

### The Role:

Software development.

### Requirements:
* C++ >= 3 years
* Knowledge of network protocols
* Experience in multithreading programming
* Logical thinking
* Good in reading English documents
* Knowledge of implementing algorithms based on RFC standards is a plus
* Experience in working in both Unix and Windows environments
* Knowledge of OpenGL, DirectX, Video/Audio codecs is a plus

### Contact:

Send CV (English) to thao.nguyen@sugar.sg. Thao's cell: +84 908386438
Company information: www.sugar.sg

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
