### ISSUE TITLE
Ruby on Rails Developer

### ISSUE THREAD

**Issue by tuyetni452** [ruby-vietnam/job_board#12]
We are currently looking to recruit an ambitious and talented Ruby on Rails developer to join us in developing a custom Content Management Platform aimed at the Saigon market.

Responsibilities will include;
= Setting up and integrating the Ruby on Rails environment
= Configuring SQL databases and data sets to our specification
= Manipulating the MVC model in accordance with our designs
= Supporting the front-end developer and designer in creating a solid UX/UI 
= Ensuring users' data remains secure throughout
= Planning for user data/behaviour monitoring
= The right candidate should be capable of displaying samples of work using the Ruby on Rails framework and integrating with SQL databases.  
= Experience with Javascript, HTML and CSS is desirable but not essential.

Strong written and spoken English is highly desirable, however we will still consider a strong Vietnamese-speaking developer if they are comfortable working closely with our staff as translators.  We can offer weekly English lessons should the candidate be interested in the opportunity.

You will be working with a friendly, ambitious and passionate team of European and Vietnamese staff who are excited to bring a unique platform to the local marketplace.  We have much experience in graphic design, website development, business management, financial markets and engaging local and international audiences.  We are currently located in a comfortable office space in Phu Nhuan.

We invite candidates to submit their CV and/or portfolio URL with a covering letter to tuyetni452@gmail.com ahead of interviews starting on the week of Monday 22nd December 2015.

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
