### ISSUE TITLE
Senior Ruby on Rails Developer 

### ISSUE THREAD

**Issue by linface** [ruby-vietnam/job_board#123]
Senior Ruby on Rails Developer 
VL Hấp dẫn xác thực trang ngành
Tin đăng trên cổng Việc làm chuyên môn Bấm đây để xemMã tin tuyển dụng: NTD1955560
 Lượt nộp: 0  Lượt xem: 147  Làm mới: 23/11/2015  Hạn nộp: 31/12/2015
THÔNG TIN TUYỂN DỤNG
 Kinh nghiệm: 3 năm
 Yêu cầu bằng cấp: Không yêu cầu
 Số lượng cần tuyển: 2
 Ngành nghề: IT phần mềm
 Địa điểm làm việc: TP. HCM
 Chức vụ: Chuyên gia
 Hình thức làm việc: Toàn thời gian cố định
 Thời gian thử việc: 2 tháng
 Yêu cầu giới tính:
 Yêu cầu độ tuổi: 25 - 29 tuổi
MÔ TẢ CÔNG VIỆC 
We are currently searching for a Senior Ruby on Rails Developer with significant experience in Ruby on Rails development backed up with solid general programming experience, exceptional problem-solving abilities, and a strong work ethic. 

You will be a part of a creative team that is responsible for all aspects of the SDLC from the initial specification, through to developing, testing and launching. As a senior developer, you are also expected to provide coaching and mentoring to your team members.

We are currently searching for a Senior Ruby on Rails Developer with significant experience in Ruby on Rails development backed up with solid general programming experience, exceptional problem-solving abilities, and a strong work ethic. 

You will be a part of a creative team that is responsible for all aspects of the SDLC from the initial specification, through to developing, testing and launching. As a senior developer, you are also expected to provide coaching and mentoring to your team members.

RESPONSIBILITIES:
• Working with a dedicated team to develop web applications using Ruby on Rails framework
• Design, build, and maintain efficient, reusable, and reliable Ruby code
• Analyze client requirements to develop functional and technical software requirements
• Develop analysis and design activities based on the SDLC and web development principles
• Help maintain code quality, organization and automation
• Supervise and support other junior developers in fulfilling tasks as well as improving their skills

QUYỀN LỢI ĐƯỢC HƯỞNG Salary is very attractive with clear review plan
Great team's support to improve expertise. Regular Techtraining and Techtalks in the company
Free Parking, coffee break, etc

YÊU CẦU KHÁC • Minimum three years experience with Ruby on Rails, along with other common libraries such as RSpec and Resque
• Strong insight into Ruby syntax and its nuances
• Solid understanding of object-oriented programming
• Able to implement automated testing platforms and unit tests
• Able to integrate multiple data sources and databases into one system. Experience with NoSQL such as MongoDB is a strong plus.
• Proficient in JavaScript and familiar with major JavaScript libraries
• Familiar with SVN and/or GIT
• Familiarity with development aiding tools such as Bower, Bundler, Rake, etc.
• Familiarity with continuous Integration, preferably Bamboo and Sonar
• Ability to work as part of a team, understand the problems of other team members, and when necessary, go above and beyond the job description to work towards a broader team goal
• Education: College or Bachelor of IT-Software or equivalent
• English: Intermediate level or above
HỒ SƠ BAO GỒM Resume and all certificate (if any)

Contact: Linh@stormcreatives.com

**Comment by huydx** [comment]
@linface bạn hãy format lại thông tin chứ đừng copy paste. Nếu không ban quản trị sẽ phải gỡ thông tin của bạn xuống.
Cám ơn.

**Comment by joneslee85** [comment]
@linface xin lưu ý là bạn nên format lại header, title theo format Mardown để đạt yêu cầu của ban quản trị đưa ra

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md

**Comment by joneslee85** [comment]
@linface i am closing this post
