### ISSUE TITLE
Golden Owl Consulting - Junior Back-end Developer (convert to Ruby on Rail) - HCM - FT

### ISSUE THREAD

**Issue by irene-ng** [ruby-vietnam/job_board#128]
## Location
* Saigon, Vietnam

## Salary Expectation
* 500-800 usd 

## Requirements
* Asp.NET MVC background
* Knowledge with Ruby On Rails is a plus
* Solid knowledge about OO
* 1+ years Software Engineering experience

### Must Have

	
•	Open-minded, love to learn new things
•	Intelligent, no one has to tell you exactly what to do, you know to get the job done
•	Take responsibility and helpful to others
•	Strong leadership skills and eager to do knowledge sharing

### Responsibilities
•	Undergo companies' training courses
•	Work on assignments and deliver in time
•	Discuss with teams and supervisors about problems and find solutions
•	Support customers on requests
•	Take part in team building activities and other company's activities
•	Contribute to company's culture

### Contact
Ms: Song Hao
Email: hr.goldenowlconsulting@gmail.com
Tel: 0917818285

**Comment by joneslee85** [comment]
your job post does not meet the format, please check the title and body header

**Comment by irene-ng** [comment]
@joneslee85 Hi, thank you for your comment, I'm new to this tool. I have already fixed the format of my job post, please take a look. Thank you so much!

**Comment by joneslee85** [comment]
@irene-ng :+1:

**Comment by joneslee85** [comment]
This post seems duplicate the #121 - please close one
