### ISSUE TITLE
Edit Suits Co. - Ruby on Rails Developer

### ISSUE THREAD

**Issue by tuyetni452** [ruby-vietnam/job_board#13]
Edit Suits Co. is a high-end made-to-measure menswear company that is revolutionizing the way men shop for clothing. We’re using an innovative combination of e-commerce and direct sales to offer our high-quality products and are dedicated to offering the best customer experience to our customers.

Skills & Traits needed by all technical applicants

- Ability to communicate in English competently. 
- Willingness and Desire to learn new technologies to build better tools and enhance user experience. 
- Willingness to take on additional roles on an ad hoc basis.
- Ability to meet deadlines. 
- Ability to clearly define specifications based on needs of users. 
- Ability to identify and fix bugs. 
- Desire to exercise creative control over feature additions. 
- Familiarity with version control. 
- Have created or is currently maintaining a production website.
- Several years of development on Ruby on Rails (Can be in a hobbyist fashion while attending University). 
- Strong server management skills with Ubuntu and Nginx. 
- Familiarity with popular gems with an ability to modify default behavior when necessary. 
- Familiarity with creating rake tasks and background jobs. 
- Familiarity with JSON datastore in Postgresql 9.3 and above. 
- Ability to write tests for feature additions. 

Benefits include flexible working arrangements depending on the candidate's ability to produce (part-time remote working). Dedicated time to learn new technologies and a meal plan. 

Expected salary: 10,000,000 VND- 30,000,000 VND. The salary is based on whether the candidate has experience and can take responsibility over certain projects. 

If you're interested, please send your CV to tuyetni452@gmail.com. We will invite the right candidates to the interview from the week of Monday December 22nd onwards.

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
