### ISSUE TITLE
Ruby Developer ($700 to $1,500)

### ISSUE THREAD

**Issue by Framgia-Vietnam** [ruby-vietnam/job_board#130]
Framgia Website:
http://framgia.co.jp/
http://recruit.framgia.vn/
http://framgia.ph/

Requirements:
        Have experience with Framework Ruby on Rails or other framework with Ruby
        Good at HTML, CSS, JavaScript (Jquery, Ajax, ...), Bootstrap, JSON, XML, ...
        Have strong knowledge about MVC, OOP. Chú trọng performance & refactoring when write code
        Have experience with Design Pattern, ORM, RESTful, TDD, ...
        Have experience with MySQL hoặc NoSQL (MongoDB, ...)
        Have experience with Redis, search engine is a plus
        Have experience with using source code GIT, SVN.
        Good with engine NginX, Unicorn, ...
        Have experience with inux/Ubuntu

Description:
       Build app for web, webservice
       Design and review source code
        Report to Project manager
        Access and will be train as Agile, Scrum model

Contact
HR team (email: hr_team@framgia.com)
0437955417 - Ms Mơ

**Comment by joneslee85** [comment]
@Framgia-Vietnam the job post does not meet the guideline, please consult the README.

I will remove this job post if no changes to be made in 1 day
