### ISSUE TITLE
Tuyển thực tập sinh/ lập trình viên .NET MVC

### ISSUE THREAD

**Issue by hmduc87** [ruby-vietnam/job_board#137]
Mô tả công việc:
•	Làm việc trực tiếp trên platform FirstStep – website kêu gọi vốn cộng đồng (crowdfunding).
•	Bạn phải trải qua 1 – 2 tháng thực tập để được hướng dẫn về tất cả các chức năng cơ bản đang vận hành của FirstStep cũng như các kỹ năng liên quan. Thời gian lâu hay ngắn là tùy bạn.
•	Hoàn thiện và tiếp tục phát triển các chức năng cho FirstStep.
•	Phù hợp với các bạn sinh viên năm cuối hoặc kế cuối.

Công việc cụ thể:
•	Tìm hiểu cách xây dựng FirstStep nói chung và cách thức xây dựng các sản phẩm phần mềm nói riêng: từ việc định hướng sản phẩm cho 100 người dùng đầu tiên tới việc sẽ mở rộng chức năng cho sản phẩm.
•	Biết cách xây dựng các biểu đồ UML cho các chức năng của sản phẩm.
•	Thiết kế cơ sở dữ liệu có chiều sâu, từ cơ bản tới nâng cao và có thể mở rộng khi dự án lớn hơn.
•	Front-end: làm việc trên nền tảng .Net MVC4-5, html, css, jquery và các api tương tác.
•	Back-end: hiểu rõ tiến trình của sản phẩm, quản lý các chức năng bổ trợ thông tin. Quan sát tiến trình dự án, xuất các báo cáo liên quan tới sản phẩm, người tài trợ, thống kê các con số phục vụ công việc và kế hoạch của Sales & Marketing.
Yêu cầu:
•	Có kiến thức nền tảng tương đối về C# .NET, MVC framework, SQL Server, LINQ
•	Có khả năng đọc hiểu tài liệu tiếng Anh tốt, chủ động tìm hiểu và trau dồi kỹ năng lập trình.
•	Hiểu biết Javascript, Html/Css, Jquery, Bootstrap là một lợi thế.
•	Chủ động trong công việc.
•	Tinh thần cầu tiến, có thể làm việc dưới áp lực.
•	Có kỹ năng làm việc nhóm.
•	Có mong muốn trở thành lập trình viên lâu dài của FirstStep.

Mô tả FirstStep:
-	FirstStep là ứng dụng trên nền tảng web responsive cho mô hình crowdfunding – mô hình kêu gọi vốn từ cộng đồng. 
-	FirstStep đã thực hiện dự án cho 3 ý tưởng tại thị trường Việt Nam.
-	FirstStep là sản phẩm nằm trong top 20 của cuộc thi Venture Cup những doanh nghiệp phát triển nhanh nhất. 
-	Ở Việt Nam, các ý tưởng là không thiếu, nhưng vấn đề tiếp cận được các nguồn vốn để mọi người thực sự có thể dần hiện thực hóa ý tưởng của mình là rất khó. Chính vì vậy FirstStep ra đời để mong muốn có thể giúp cho thị trường các ý tưởng Việt Nam có thể có được sự giúp đỡ từ cộng đồng cũng như để cộng đồng của chúng ta có thể có được những dự án thực sự hay ho để trải nghiệm.

Tại sao bạn nên tham gia với FirstStep team:
FirstStep hiện đang trong giai đoạn là một startup của mảng công nghệ, khó khăn về mọi thứ là rất nhiều, tuy nhiên chính những khó khăn đó lại là cơ hội cho các bạn phát triển được khả năng nhiều hơn. Đồng thời việc phát triển crowdfunding tại Việt Nam là một thử thách lớn và thành quả mang lại có ý nghĩa lớn không chỉ cho người tham gia mà còn cho cộng đồng. Nếu bạn muốn nâng cao tay nghề và không ngại thử thách thì hãy tham gia vào đội ngũ của FirstStep để có được nhiều cơ hội trải nghiệm như:
•	Môi trường làm việc Startup, trải nghiệm các vấn đề mà startup công nghệ vướng phải, các hướng xử lý. Biết được thế nào là sự tăng trưởng của các nền tảng công nghệ “From zero to hero”.
•	Được làm việc trên sản phẩm thật, luôn luôn thay đổi để phù hợp với thị trường, với khách hàng
•	Phát triển kỹ năng theo chiều sâu – chuyên sâu vào nền tảng .Net MVC
•	Phát triển kỹ năng theo chiều rộng với đa dạng các kiến thức cũng như công nghệ được ứng dụng.
•	Hướng dẫn về tất cả các chức năng cơ bản đang vận hành của FirstStep cũng như các kỹ năng liên quan.
•	Có cơ hội tham gia vào đội ngũ của FirstStep.
Thông tin khác:
•	Số lượng tuyển: 2 – 4 bạn
•	Thời gian: hạn chót liên hệ hoặc gửi CV tới cho chúng tôi là 15/1/2016
•	Vui lòng thực hiện bài test tính cách tại link này: http://www.humanmetrics.com/cgi-win/jtypes2.asp và gửi kèm cho chúng tôi theo thông tin liên hệ hoặc CV của bạn.
•	Email nhận hồ sơ hoặc thông tin: info@firststep.vn
•	Mọi thắc mắc có thể liên hệ trực tiếp số đt: 09.1899.1827 gặp a. Đức

**Comment by joneslee85** [comment]
bài post không đạt đúng yêu cầu, mong bạn thay đổi cho đúng format

mình sẽ xoá bài trong 24h nếu không có thay đổi

**Comment by hmduc87** [comment]
Cho mình hỏi sai format gì vậy ad :).

**Comment by hnq90** [comment]
@hmduc87 Có vẻ là tiêu đề: [Company Name] - [Job Title] - [Location] - [Job Type]
Format ở đây này: https://github.com/ruby-vietnam/job_board/blob/master/README.md
