### ISSUE TITLE
Web and web application programmers/developers

### ISSUE THREAD

**Issue by AdamWidmer** [ruby-vietnam/job_board#16]
We're a US based web development company that's looking to expand our operations by contracting out some of our work to Vietnamese programmers. We specialize in building websites and applications for small-medium size businesses in several industries, ranging from hotels to law firms. We also assist in launching early stage startups.

Any developer/ programmer, or designer can join our team with the following skills in:

1. Very highly desired: Ruby, Python, Javascript, JQuery
2. Highly desired: LAMP, HTML5, Java
3. Desired: CSS, CSS3, HTML, Photoshop, Illustrator, Wordpress, Drupal, Joomla, C++, C#, Objective C

Interested candidates send application package to vietnamdevpro@gmail.com, including:
• CV
• Portfolio
• Code for review - this may either be sent to us as raw code that can be opened in a text editor or they can link to a repository such as GitHub.
• Contacts of at least 3 references

**Comment by joneslee85** [comment]
@AdamWidmer can you please provide the name of your company and URL to your company?

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
