### ISSUE TITLE
TINYhr - Ruby Devs Join Us - $2,000 to $3,500

### ISSUE THREAD

**Issue by dhajdu** [ruby-vietnam/job_board#17]
## Location

* Ho Chi Minh, Vietnam
* http://www.tinyhr.com/this-is-why-you-should-work-here

## Pay and Benefits
* $1500 to $3500 per month based on experience
* Full coverage, International Health Insurance
* Flexible work schedule and holidays - But we will work very hard
* Shiny new macbook pro + smart phone

## Core Values
We live and breath by these values and are looking for team members who share this spirit and want to work for a values driven company like TINYhr. 

* D elight customers
* E lect and spread positivity
* L ead with solutions and embrace change
* I ncrease communication with transparency
* G o the extra mile with passion
* H old oneself accountable "Big Freedom = Big Accountability"
* T reasure culture and freedom

## Requirements
* Solid Ruby Skills
* Bachelors in Computer Science
* Strong DB Design
* 5+ years Software Engineering experience

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Working on our core product, TINYpulse.com
* Building out the server side hooks for the mobile app
* Contributing to feature design and product road map
* Helping us build out the most amazing software office in Vietnam

### Contact

dhajdu: Dave Hajdu - dave@tinyhr.com - +84 90 995 8581

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
