### ISSUE TITLE
Framgia Vietnam - Ruby Devs Join Us - $ 500 to $1,500 

### ISSUE THREAD

**Issue by Framgia-Vietnam** [ruby-vietnam/job_board#19]
Framgia Vietnam - Ruby Devs Join Us - $ 500 to $1,500 

## Location

* Hanoi, Vietnam

## Requirements
 - Have university/college degree in IT

### Must Have

* Have experience with Framework Ruby on Rails or other framework with Ruby
 - Good at HTML, CSS, JavaScript (Jquery, Ajax, ...), Bootstrap, JSON, XML, ...
 - Have strong knowledge about MVC, OOP. Chú trọng performance & refactoring when write code
 - Have experience with Design Pattern, ORM, RESTful, TDD, ...
 - Have experience with MySQL hoặc NoSQL (MongoDB, ...)
 - Have experience with Redis, search engine is a plus
 - Have experience with using source code GIT, SVN. 
 - Good with engine NginX, Unicorn, ...
 - Have experience with inux/Ubuntu
 

### You’ll be responsible for

*  Build app for web, webservice 
- Design and review source code 
- Report  to Project manager 
- Access and will be train as  Agile, Scrum model

### Contact

HR team (email: hr_team@framgia.com)

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
