### ISSUE TITLE
Alt Plus Vietnam Co.,Ltd - 5 Senior Dev Ruby

### ISSUE THREAD

**Issue by vietanhph** [ruby-vietnam/job_board#2]
## Requirements
* 2+ years to code Ruby
* Good English reading skill (Japanese speaking is an advantage)
* Have good knowledge in basic coding

## Skills
* Make specification/design for system
* Have experience with WEB coding, problem-solving related to performance and security for WEB

### Must Have
* Be in love with game
* "Dare to challenge, dare to fail"

### Responsibilities
Great power comes with great responsibilities!

### Contact
Ms. Viet Anh - Recruitment Lead
Email: anh.pv@altplus.com.vn
FB: www.facebook.com/gaugu.me
Mob:+84-936-368-969
Skype: anhpvh

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
