### ISSUE TITLE
Pure Solutions - 2 JUNIOR BACK-END DEVELOPERS (Competitive Salary)

### ISSUE THREAD

**Issue by PUREvacancies** [ruby-vietnam/job_board#20]
## Location

* TP.HCM, Vietnam

## Requirements
• Good experience in PHP and/or Node.js is prerequisite requirement  
• Experience in Web Application technologies like HTML5, CSS, JavaScript  
• Strong background in SQL databases (preferably MySQL, MongoDB is a plus)  
• Ability to work both independently and as a team worker  
• Analytical and problem-solving skills, creative, self -motivated, result –oriented  
• Willingness to learn new technologies both by training and self-learning

### Ideally
• Experience in at least one of the following web-application frameworks: Zend; Knowledge in Ruby on Rails is a plus
• Experience in MongoDB, Redis
• Experience in jQuery, Angular JS and mobile based HTML5 applications is a plus
• Familiarity with REST/SOAP/XML-RPC 
• Experience in development tools (Git, SVN, JIRA, Jenkins)  

### Responsibilities
• Participate as developer in web & mobile development projects for international customers under supervision of our project manager. 
• Perform maintenance and support tasks on existing web application systems and mobile apps upon request  
• Assist in the analysis of problems as defined by the business consultants and design suitable solutions 
• Performing tasks related to implementing, documenting and deploying software components 
• Assist in software testing activities and cooperate closely with QA-staff in finding and fixing software errors

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
