### ISSUE TITLE
LHV Software - Ruby System Developer

### ISSUE THREAD

**Issue by nbthangbk** [ruby-vietnam/job_board#21]
## Location

* Ho Chi Minh, Vietnam

## Requirements
* Ruby
* Excellent logical thinking ability.
* Ability to work in a team.
* Excellent knowledge of Object oriented programming (OOP), Algorithms, Data Structures.
* Good problem solving, collaboration, and communication skills.
* Experiences with networking programming and database programming (SQL)
* Deep understanding of web application architecture, including TCP/IP and HTTP
* Years of experience: 2 year(s)

## Skills
* Shell scripting
* NoSQL Databases, Hadoop
* IaaS technologies and virtualization: AWS, VirtualBox, VMWare, KVM, zones/containers, Vagrant

### Responsibilities

* Integrate software with existing systems
* Responsible for troubleshooting application related issues and insuring/maintaining high performance.
* Develop internal & appropriate external documentation content.
* Ensure conformity of work to software quality standards.
* Provide assistance to Support Engineers with customer support tasks.

### Contact

Thang Nguyen: nbthang_bk@yahoo.com (01298175186)

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
