### ISSUE TITLE
TINYpulse - Senior Ruby Developer - $2500 To $4000 A Month-Email me at dong@tinyhr.com

### ISSUE THREAD

**Issue by hoangngocdong** [ruby-vietnam/job_board#22]
Job Description
"TINYpulse is the single best tool I have ever used in 20 years of
business ownership for understanding the mindset of my team and
heading off problems before they become unmanageable." -Chuck Bender,
CEO of Skynet Broadband

TechCrunch, WSJ, Fast Company and other have covered the
inspiration and growth of TINYpulse (just do a Google News search to 
see our growing list of accolades and press). We provide leaders a pulse on how
happy, frustrated, and burnt out their team is before retention sinks
and issues become cancerous. Our mission is simply to "make employees
happier" because we believe when that happens, retention, engagement,
and results all improve.

http://www.tinyhr.com/this-is-why-you-should-work-here

We just received a major round of funding ($3.5MM USD) to accelerate our growth from Baseline Venture Capital and 9 other strategic investors. 

You will get to work with the best advisors in Silicon Valley, an amazing team in Ho Chi Minh and Seattle, with the best equipment in a comfortable working environment. 

Each team member gets stock options, a smart phone, shiny new Macbook Pro, top salary, and international medical insurance. 

The following is our cultural values that we live by and make decisions. We also donate 1% of our time to the community, 1% of our products to non-profits, and 1% of our profits to a non-profit. Please apply only if the following values feel good to you:

D elight customers
E lect and spread positivity
L ead with solutions and embrace change
I ncrease communication with open engagement
G o the extra mile with passion
H old oneself accountable
T reasure culture and freedom

As for background, you'll get to work shoulder-to-shoulder with the founding team. The company was started by David Niu, an angel investor and serial entrepreneur, who started NetConversions (sold to "AQNT") and BuddyTV. We launched only a couple years ago and have clients all around the world, including GlaxoSmithKline, HubSpot, Brooks Running, and Deloitte. Given our rapid growth, we're looking for talented, driven team members to help our tiny team make a BIG impact.
Job Requirement
We need talented and passionate people to join our journey. Do you love helping others solve problems? Do you think "Impossible" means "I'm possible?" Do you enjoy working with a tiny team to make a BIG impact?

If so, we're looking for a full-time Ruby on Rails developer. Some of the characteristics of a great candidate:
-Brilliant coder and architect
-Views problems as opportunities for innovation versus roadblocks
-Enjoys continual learning and growth
-Leads by example
-Infectiously positive attitude to the team and clients
-Seven + years of software development experience

In addition:
* You have an eye for simple, intuitive web interactions. It's important to us to keep our tool simple and intuitive for our users. We realized most developers aren't designers, but it's important that we always think through the user experience of the features we add.
* You're able to identify and discuss the relative tradeoffs a feature has on a the product. How features impact the complexity of the user interface? How we message it for adoption? How it affects to future customer support frequency? How much technical debt it incurs in the codebase? We want you to be an active participant and think how our features delight our customers.
* You're familiar with testing Ruby apps and value test coverage in a codebase
* You're proud of your craft and are conscientious about code style conventions, writing DRY code, factoring out code into libraries, and naming functions and constants in intuitive ways
* You're comfortable troubleshooting deployment issues and connectivity issues between us and our third party providers. There may be times when you will be the one to troubleshoot unexpected production issues.
* You're friendly and professional when communicating with customers over support issues. They love us so it's hard not to be.

If you're interested in this role, please provide the following:
(a) Two examples (preferably from your previous employment) where you have exemplified our cultural values above
(b) Why you would be a great fit and be excited to jump into our fox hole with our small team
(c) Your resume
(d) When you'd be able to start
(e) Required compensation

Email me at dong@tinyhr.com or ring me at 0944705031

**Comment by rauxalach** [comment]
:+1:

**Comment by duythien** [comment]
+1

**Comment by joneslee85** [comment]
Good luck to all talented dev :+1: Flaunt your skill and get the reward that you deserve!

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
