### ISSUE TITLE
Storytree - Senior iOS developer - $2000/month, stock option included, Silicon valey startup

### ISSUE THREAD

**Issue by kiennt** [ruby-vietnam/job_board#23]
Storytree is a technology company that builds simple, delightful mobile experiences to help users share the important moments in their lives. Our iPhone app SimplePrints has been downloaded over 1 Million times and is growing rapidly in the US market. We will be launching an Android version and are expanding to Europe. We are growing our teams in Hanoi, Vietnam and Silicon Valley to deliver high quality products to our customers.

Our company has appeared in the New York Times, USA Today, Techcrunch, and our apps have been featured by Apple and recognized at SXSW. We are backed by 500 Startups, angel investors, and great advisors such as Dave Bagshaw (former CEO of Shutterfly), Gentry Underwood (founder of Mailbox) and Semyon Dukach (founder of SMTP).

We are currently focused on growing SimplePrints, the easiest way to create a photo book from your mobile phone. Over the past 12 months SimplePrints has grown to 1M users and annually generates millions of USD in revenue.

1. Work with an exceptional team that supports learning and personal growth. 
2. High impact on our business and growth. 
3. Competitive compensation. 
4. Generous vacation and paid leave. 
5. High personal growth potential. 
6. Flexible working hours. 
7. Lunch allowance.

If you're interested in this role, please provide the following:
(a) Two examples (preferably from your previous employment) where you have exemplified our cultural values above
(b) Why you would be a great fit and be excited to jump into our fox hole with our small team
(c) Your resume
(d) When you'd be able to start
(e) Required compensation

Please send CV to my email: trungkien2288@gmail.com

**Comment by joneslee85** [comment]
@kiennt You do not provide a contact details

**Comment by kiennt** [comment]
Could you guys send our CV to my email: trungkien2288@gmail.com

I am looking forward to work with awesome iOS developer from our community

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
