### ISSUE TITLE
Sugar Ventures - Ruby on Rails Engineer in Ha Noi - $1000 to $2500

### ISSUE THREAD

**Issue by krukgit** [ruby-vietnam/job_board#24]
## Location
Ha Noi, Vietnam

## About us
We’re a startup studio creating our own products and seeing them through the infancy age. We’re headquartered in Singapore but recently opened a development office in Ha Noi.

The team is small and every employee has a big impact on the products and the company. Most of our products are mobile-centric but we have a project for everyone - social media, marketplaces, video, P2P, RTB, etc.

You can see our released products at http://www.sugar.sg/ 

## Role
We are looking for a Ruby on Rails developer with experience working with AWS, Linux and PostgreSQL. DevOps or front-end experience a big plus. 

You will need to be able to develop Ruby on Rails web applications and REST APIs from scratch, including setting up and maintaining the necessary infrastructure (AWS EC2, S3, RDS, IAM).

## Requirements
* 2 years of Ruby on Rails experience
* Experience working with Amazon Web Services
* Experience working with PostgreSQL or MySQL
* Experience working with Unix operating systems
* Ability to work independently and within a team
* Ability to work in an English only environment
* Good communication skills
* Good problem solving skills
* Attention to details
* Knowledge of HTML, CSS, JavaScript, jQuery, Ember.js, AngularJS, Bootstrap a plus
* Knowledge of Capistrano, Chef, Puppet, Docker, Ansible a plus
* Degree in Computer Science or related field

## Ideal candidate:
* Can develop and maintain Ruby on Rails application with supporting infrastructure
* Delivers projects on time, within budget and to required quality standards
* Works well with a team but can work independently when required
* Interprets requirements and yields solid design specification, within existing frameworks
* Implements efficient and effective solutions from design specifications
* Effectively tests developed software
* Architects/designs new solutions when required
* Can make design decisions that ensure future scalability while taking into account current budget  
* Provides accurate estimates of the effort required to complete a task
* Produces and maintains high quality documentation
* Recommends and implements process improvements

## Contact
If you’re interested please send us your CV at jobs@sugar.sg

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
