### ISSUE TITLE
PlayNhé.com - Ruby on Rails or Front-End Hackers (HN, HCM)

### ISSUE THREAD

**Issue by tiendung** [ruby-vietnam/job_board#25]
# PlayNhé.com - Ruby on Rails Hacker (HN, HCM)

Mới ra đời 24/12/2014 nhưng với nội dung www.playnhe.com/boituoi đạt hơn 3 triệu lượt tương tác trên Facebook chỉ sau 2 tuần và nhiều nội dung viral tương tự, playnhe.com đã trở thành platform được chia sẻ nhiều nhất trên Facebook tại Viêt Nam tháng 1/2015 với lượng traffics lên tới hơn 1 triệu pageviews mỗi ngày. Platform này được phát triển bởi Alex Nguyen, một trong những người Việt Nam đầu tiên dùng Ruby on Rails từ những năm 2006. Hiện chúng tôi đang cần tìm thêm những lập trình viên có năng khiếu và đam mê để phụ Alex phát triển những tính năng sâu hơn cho platform. Đương nhiên là chúng tôi sẽ trả lương xứng đáng cho bạn nhưng có lẽ bạn cũng nên trả học phí cho chúng tôi để học được nhiều điều từ Alex và PlayNhé.

Hẹn gặp lại bạn ở phía bên kia cầu vồng ;)

## Location

* Hanoi, Vietnam
* Saigon, Vietnam

## Requirements
* JavaScript
* HTML5
* Ruby
* NoSQL (MongoDB, Redis, CouchBase ...)

### Must Have

* Tâm hồn rộng mở để đón nhận cái mới
* Kiên trì để đạt tới thành công cuối cùng

### Ideally

* Có tư duy làm sản phẩm
* Có tư duy marketing
* Có kinh nghiệm scale hệ thống lớn vài triệu pageviews / ngày

### You’ll be responsible for

* Phát triển các tính năng nâng cao cho www.playnhe.com

### Chiến thôi!
![fight](https://cloud.githubusercontent.com/assets/8133/5918130/c3c32d4e-a657-11e4-9b8d-478ad5b0e47f.gif)
 
### Contact

Alex: dungtn@gmail.com (+84 903068888)

**Comment by tiendung** [comment]
Đã tìm được 3 ứng viên và tiếp tục tìm kiếm thêm.

Cám ơn Cộng Đồng RubyVietnam nhé!

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
