### ISSUE TITLE
PLZ - iOS developer - Hanoi - Sports Apps related

### ISSUE THREAD

**Issue by nguyenchiencong** [ruby-vietnam/job_board#26]
Today, **sports teams leverage sports data to become more efficient, bookmakers leverage those same data to become more accurate at odds making**. What about the sports fans? 
This is a train not to be missed. The world of sports is undergoing some big changes and we want to be ahead in the trend. **Essentially, we leverage technology and data to help sports fans make useful forecasts and make it fun inside a social network built on the same passion for sports**.
Our web app and API is growing and we need you to help us design our architecture and prepare the launch of PLZ applications.

## Responsibilities:

* Work closely with our programmers and designers to customize the user experience for the iOS app.
* Analyze and optimize UI and the application code for efficiency and performance.

## Requirements:

* 2+ years of object-oriented software development experience.
* 1+ years building complex applications for the iPhone or iPad using Objective-C with Cocoa and other frameworks.
* Ability to understand and debug large and complex code bases.
* Experience dealing with or designing clean and maintainable APIs.
* Experience writing unit tests and testable code.
* Knowledge of iOS SDK performance tools and optimization techniques.
* Excellent problem solving, critical thinking and communication skills.
* Be positive minded about work and cooperation with team mates! We do not want pessimists who block at every obstacle.
* Most importantly, you MUST have a growth mindset: http://sivers.org/mindset

## Why You'll Love Working Here:

* Competitive salary.
* Awesome startup culture.
* Great growth potential.
* Work with a young and very motivated team.
* We are a highly energetic startup and you will have huge impact in our business and growth.

## Some last words:

* We're a startup and a small team, we have advisors, investors and partners.
* We are hardcore believers in company culture and do not mess around with toxic disruption of our culture.
* We'll be growing very fast in the coming year.
* Do not be afraid of learning nothing because of hopping from project to project as we are not an outsource company. You'll have many new challenges.
* We intend to become an Unicorn ($1B+ company) and you'll be an important part of that rise. Growing in Vietnam is just a start for a worldwide expansion.

If you feel fit for this position, we'd love you to be part of this exciting journey. Drop us an email with your CV at contact@plz.vn if you are interested.

For others, please help us by sharing this message or introduce us to the right people.

Thanks and cheers.

**Comment by thangdq88** [comment]
Cần freelancer iOS thì pm em nhé :D 
Skype: thangdq88
Thanks

**Comment by nguyenchiencong** [comment]
Cảm ơn bạn nhưng bên mình không tìm Freelancer.
Thanks
