### ISSUE TITLE
Front end web developer - US financial project 

### ISSUE THREAD

**Issue by namproctin** [ruby-vietnam/job_board#27]
Hello , I am looking for 1-5 front end web developers to join our team for an US financial web project . NEW GRADUATES ARE WELCOMED . Join us , you can WORK AT HOME and only have to come to office once per week for discussion . 

Expected skills:
HTML5 , CSS3 , AngularJs , Bootstrap , great web design skills are a plus 

Company location :
Tan Binh district , HCM
Working time : you have your own freedom to choose .

Please email me namproctin@gmail.com for more details .

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
