### ISSUE TITLE
MISFIT WEARABLES - Back-end Developer (MongoDB talents wanted)

### ISSUE THREAD

**Issue by hoangtriminh** [ruby-vietnam/job_board#29]
Please send your resume to people@misfit.com

As a Misfit developer, you'll be contributing to the development of next-generation wearable products to improve peoples' health and well-being, while participating in the most innovative engineering team in Vietnam.

Misfit Wearables Corporation is a US high-tech company inventing and manufacturing wearable and ambient computing products, with R&D and operations office in Vietnam. The company was founded in 2011 by Sonny Vu and John Sculley (the former CEO of Apple and Pepsi). 

More information can be found at:
www.misfit.com 
https://www.youtube.com/watch?v=aybITzID3bM 
http://tuoitre.vn/tin/nhip-song-tre/lang-nghe-giac-ngu-va-nhip-tho-de-khoi-nghiep/663892.html

WHAT YOU WILL DO
o	Develop and maintain the core functional logic and operations of our system. 
o	Ensure that the data or services requested by the front-end system or software are derived programmatically.
o	Create and maintain the back-end consisting of the core application logic, databases, data and application integration, API and other back-end processes.
o	Perform testing and debugging of any back-end application or system.
o	Join different projects to prepare for the expansion of the Misfit online business.

WHAT WE EXPECT FROM YOU
o	BS, MS, or PhD in Computer Science or equivalent.
o	Exceptional software engineering talent.
o	Must have experience pulling and prepping data from multiple databases as well as formatting for visualization.
o	3+ years of API experience.
o	Deep knowledge of large scale backend development.
o	3+ years of Java/NodeJS/Python/Ruby experience.
o	2+ years of SQL or other relational database structures.
o	2+ years of Mongo DB.
o	Ability to work independently or as a team member.

IN RETURN WE OFFER

o	A cool, innovative working environment and talented colleagues.
o	Competitive base salary (based on skill levels):
▪	Entry Level: 500-800 USD/month
▪	Mid Level: 600-1,200 USD/month
▪	Senior Level: 1000-2,500 USD/month
o	Mac/Windows, iOS/Android, you name it.
o	Personal and professional development opportunities: more than 30 engineers have been sent to Silicon Valley for 1-2 month(s) training.
o	Many other benefits (gym, iPhone, health subsidies and overseas travel).

**Comment by joneslee85** [comment]
One of the rules of job board is to be specific as much as possible. Do you have any idea which stack/language that Misfit will be using?

**Comment by joneslee85** [comment]
Furthermore, is this job related to MongoDB only? The job description seems a bit broad.

**Comment by hoangtriminh** [comment]
Dear Mr. Trung,

I'd like to thank you for your feedback. Honestly, I'm not a technical guy
and all the JDs had to be composed by the tech team. I 'm working with my
technical team to have a more specific JD.

Best regards,

Marcus

**Comment by hoangtriminh** [comment]
Dear Mr.Trung,

The back-end job description is a bit broad because we are still have many
open vacancies with different requirements, and at this moment, our
priority is looking for a candidates with good knowledge and experience in
MongoDB.

Best regards,

Marcus

**Comment by joneslee85** [comment]
@hoangtriminh I see. I think you should ask your tech to revise the requirements because this job description would not sell well to good developers, especially those who are good at things like MongoDB, they tend to be quite picky and if the company could not get the job description right, it is unlikely you would get to right talents.

**Comment by hoangtriminh** [comment]
Dear Mr.Trung,

Can you send me a sample of an ideal JD for a specific position, please ?
I will follow it to build better JDs.

I'm a recruiter and have very limit knowledge about technical. Can I invite
you a cup of coffee at weekend ? I'd like to learn more to have better
knowledge in technical to consult my technical team about HR, it's hard to
collaborate with them without any understanding about them.

Thank you and best regards,

**Comment by hoangtriminh** [comment]
Hi Mr.Trung

In Misfit we are using the following stack/language.
Ruby On Rails framework
Javasript dùng Foundation

Thank you for your support

**Comment by joneslee85** [comment]
@hoangtriminh I love to catch up with you one day when I visit Vietnam. If you know the details of the job, please update the description accordingly.
