### ISSUE TITLE
MISFIT WEARABLES - Front-end Developer (Node.JS and Magento savvy)

### ISSUE THREAD

**Issue by hoangtriminh** [ruby-vietnam/job_board#30]
Please send your resume to people@misfit.com

As a Misfit developer, you'll be contributing to the development of next-generation wearable products to improve peoples' health and well-being, while participating in the most innovative engineering team in Vietnam.

Misfit Wearables Corporation is a US high-tech company inventing and manufacturing wearable and ambient computing products, with R&D and operations office in Vietnam. The company was founded in 2011 by Sonny Vu and John Sculley (the former CEO of Apple and Pepsi). 

More information can be found at:
www.misfit.com 
https://www.youtube.com/watch?v=aybITzID3bM 
http://tuoitre.vn/tin/nhip-song-tre/lang-nghe-giac-ngu-va-nhip-tho-de-khoi-nghiep/663892.html

WHAT YOU WILL DO
o	Develop features of the Misfit website, following design principles and web architecture.
o	Ensure the smooth and effective operation of Misfit website functions.
o	Develop software/tools to support the online business.
o	Join different projects to prepare for the expansion of the Misfit online business.

WHAT WE EXPECT FROM YOU
o	Bachelor Degree in Information Technology, Computer Science, or equivalent.
o	At least 1 year of relevant working experience.
o	Knowledge of:
▪	General HTTP and web knowledge: session, cookies, HTTP protocol, RESTful, etc. 
▪	Javascript : DOM , jQuery / AJAX, CSS3/HTML5. 
▪	Server-side scripting language : NodeJS/PHP/Java/Python. 
▪	Server-side MVC framework : Sails JS/Total JS/AngularJS/Yii/ZendFrameWork. 
▪	Common relational DB concepts and SQL : index, trigger, store procedure, foreign key, table joins, etc.
o	Huge plus for Misfit: strong English communications skills.

IN RETURN WE OFFER
o	A cool, innovative working environment and talented colleagues.
o	Competitive base salary (based on skill levels):
▪	Entry Level: 500-800 USD/month.
▪	Mid Level: 600-1,200 USD/month.
▪	Senior Level: 1000-2,500 USD/month.
o	Mac/Windows, iOS/Android, you name it.
o	Personal and professional development opportunities: more than 40 engineers have been sent to Silicon Valley for 1-2 month(s) training.
o	Many other benefits (gym, iPhone, health subsidies and overseas travel).

**Comment by joneslee85** [comment]
We are not taking any position that is related to PHP, so if possible can you please any mentions to PHP? Many thanks
