### ISSUE TITLE
[HCM] Ruby on Rails Leader (500$ ~ 1000$)

### ISSUE THREAD

**Issue by viet-recruit** [ruby-vietnam/job_board#31]
## Location
Ho Chi Minh, Vietnam

## Requirements
- At least 3 years on Web engineer (Including RoR)
- Experience in managing team (at least 3 members) as a leader in at least 0.5 year
- English level: reading and writing is fluently
- Japanese skill is not required but Japanese skill is a plus

## Responsibilities
- Leader of developing Web apps team (RoR, Team size: 2-5 members)
- Managing projects for Web application development (RoR)
- Taking a responsible for motivating the projects such as: understanding specification, managing 
the project progress, leading technologies, managing team members, communicating with 
customers, supporting coding, etc.
- More details through the direct interview..

## Contact
Please send us your CV to: andy@jobseeker.vn

Details info please see: https://www.facebook.com/vietrecruit/posts/702601576519141?fref=nf&pnref=story

Thank you!

**Comment by joneslee85** [comment]
@viet-recruit can you please provide the name of the company?

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
