### ISSUE TITLE
Công ty Cổ phần Tinh Vân - Ruby Developers - Redmine extension developer

### ISSUE THREAD

**Issue by toannm** [ruby-vietnam/job_board#32]
Số lượng: 05 lập trình viên
 Mô tả công việc:
-	Công ty đang có nhu cầu tuyển 05 Lập trình làm Ruby On Rails
-	Tham gia phát triền dự án theo yêu cầu của Công ty
-	Làm việc tại Hà Nội

Yêu cầu công việc:
-	Có kinh nghiệm làm dự án về Ruby ít nhất từ 6 tháng trở lên
-	Có kiến thức tốt về các Ruby Frameworks
-	Đã từng phát triển extensions cho Redmine là một lợi thế
-	Nắm chắc về Database My SQL, Linux, Ubuntu
-	Ưu tiên ứng viên có thể đi làm được ngay

Quyền lợi:	     
-	Mức lương từ 600$ đến 1.000$ tùy vào năng lực và kinh nghiệm. Sẽ thỏa thuận khi phỏng vấn.
-	Lương cạnh tranh thỏa thuận theo năng lực, thưởng lễ, Tết định kỳ hàng năm, thưởng hiệu quả kinh doanh dự án. 
-	Hưởng chính sách xét lương 2 lần/ năm và đột xuất nếu hoàn thành xuất sắc nhiệm vụ;
-	Có cơ hội được hưởng các chế độ đãi ngộ đặc biệt theo chính sách Nhân sự Key của Tinhvan Group;
-	Có cơ hội hưởng quyền mua cổ phiếu ưu đãi theo Chính sách của Công ty;
-	Có cơ hội đi học tập và làm việc tại Singapore và Nhật Bản.
-	Được tham gia các lớp học tiếng Nhật từ sơ cấp tới nâng cao sau giờ làm việc tại công ty
-	Có cơ hội trở thành “Gương mặt xuất sắc” hay “Minh Tinh” tiêu biểu của Công ty nếu hoàn thành xuất sắc nhiệm vụ;
-	Hưởng đầy đủ các chính sách và chế độ như: BHYT, BHXH, BHTN,.. theo đúng quy định của Bộ Luật Lao động và của Công ty;
-	Hưởng chế độ nghỉ mát 1 lần/năm, có chế độ thăm hỏi sức khỏe cho bản thân và người nhà theo Chính sách đãi ngộ của Công ty;

Hồ sơ dự tuyển gồm: 
Gửi Cv vào email: phuongvt@tinhvan.com , ghi rõ điện thoại và địa chỉ liên hệ, trình độ chuyên môn và kinh nghiệm các dự án đã làm, ảnh 4x6; 

Địa chỉ nộp hồ sơ:   Công ty Cô phần Xuất Khẩu phần mềm Tinh Vân
Tầng 4, Khách sạn Thể thao, Làng Sinh viên Hacinco, Thanh Xuân, Hà Nội.
Tel:  62852502 máy lẻ 34 (gặp Mrs Phượng); E-mail: phuongvt@tinhvan.com
Chi nhánh: Tầng 4 D1 Tòa nhà Mirae Business Center 268,Tô Hiến Thành, P 15, Quận 10, TP HCM.

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
