### ISSUE TITLE
RobustTechHouse Singapore FinTech Consultancy - Remote RoR Developer (USD900-1100 and project bonus)

### ISSUE THREAD

**Issue by khianhao** [ruby-vietnam/job_board#34]
## About

We are a very exciting and innovative Financial Tech startup (http://www.robusttechhouse.com/) and consultancy in Ho Chi Minh and Singapore building next-generation Financial applications across E-Commerce, Trading, Portfolio Management, Wealth Management, Banking etc. We will re-invent the FinTech landscape in Asia. We need YOU, as our pioneering development extraordinaire and technopreneur, to help us build our robust software and team.

* Flexible - Very flexible working hours and locations. You can work from home if you want because we trust you.
* Great Team - You work directly with our excellent team in Ho Chi Minh and Singapore. 
* Increase Your Value - You get to work on Financial applications and learn about finance and investments on the job. We would love to train you on financial concepts and increase your financial knowledge. This will substantially boost your personal skills and value for your future jobs.
* High Visibility - Your opinions & suggestions will be heard and you will help shape the company.

## Location

HCM, Remote

## Responsibilities

To work closely with our team in Ho Chi Minh and Singapore to design, implement and support our web platforms in RoR

## Skills

* Technical hands-on development experience in RoR
* Exceptionally passionate about technology
* Strong interest in Finance, Financial applications, Trading or very good with numbers
* Detail-oriented and takes pride in crafting software that is robust and efficient
* Degree in Computer Science, Information Systems, or a related field
* Full-time (40 hrs a week) preferred but willing to consider exceptional candidates on part-time (20 hrs a week)

## Contact

Please send your resume, geek cred (GitHub links, code samples, project portfolio descriptions etc), MD5 hash of the string "RobustTechHouse" to matt@robusttechhouse.com

**Comment by Gnouc** [comment]
Is it fine for people with low experience with ROR but have good knowledge about Ruby?

**Comment by joneslee85** [comment]
@Gnouc I don't think it would be a problem though, RoR can be pick up quite quick.

**Comment by khianhao** [comment]
If you are interested to learn RoR and have prior experience in other web languages or Ruby, please apply as well :) Thanks.
