### ISSUE TITLE
HCM - Full Stack Ruby on Rails Developer

### ISSUE THREAD

**Issue by danielvester** [ruby-vietnam/job_board#36]
## Description
We are a startup from germany who is looking for an experienced Full-Stack Ruby on Rails Developer to join our team in developing an innovative new audio distribution platform.

As the lead developer in our team, you will play a critical role in the architecture, design, development, and deployment our applications and services.

## What will you do?

* Work together with UX/UI designers and Project Managers to implement the latest new features for our application.
* Specify and develop the API which we will use to integrate our service into 3rd party products.
* Implement the payment system.
* Manage and maintain the backend and servers.
* Scaling the application.
* Documenting all your work (instructional, technical specification)
* Keeping up-to-date with industry issues and trends – accessibility, usability, emerging technologies etc – and informing the team when new technology can be implemented into forthcoming projects.

## Your Skills and Experience
* You have at least 2-5 years work experience in the software development industry.
* You love playing with back-end logic and enhancing front-end user experience.
* You have excellent written/spoken english skills.
* You have experience working with Agile SCRUM methodologies (we are using Jira and greenhopper)
* You have a BS Degree (Advanced Degree is beneficial)

### Technical
* Must be experiences in Ruby on Rails for web development.
* Must have a good understanding with Amazon AWS, especially RDS, EC2, S3, SES
* Must have a good understanding of HTML 5, CSS3, SASS, Jquery, Ajax, bootstrap, javascript, CoffeeScript
* You are able to tackle security and scalability of large projects.
* Experience with designing databases, preferably MySQL.
* Experience with search engines, preferably Elasticsearch (Lucene)
* Experienced with web service protocols such as HTTP, REST, SOAP, JSON.
* Experience in Testing, Test Driven Development and Pair programming. 
* Experience with Git/Bitbucket.
* Experience with iOS or Android (for Mobile Development) is a plus.

## Why you’ll love working with us
* We have a fun startup culture that values openness, creativity and awesomeness.
* You’ll be part of a team that’s building an innovative new product.
* You will have exciting responsibilities.
* You will have an attractive salary and annual salary reviews.
* You will have flexible working hours and a flexible working location.
* Minimal meetings. We do one quick Sprint planning meeting every week and you will have the occasional meeting to hash out ideas with the design team, but that’s it.
We love music, and we hope you do to!

## Apply Now
If this sounds like you then please get in touch! One of our team members will be in Ho Chi Minh conducting interviews for the next couple of weeks, so get in touch quickly.

To apply, please fill out this very simple [Google Form] (https://docs.google.com/forms/d/1ZBKlGX336mUbAk0mXbSRiu2fF8r-RgCJJxDMns7y6LE/viewform)

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
