### ISSUE TITLE
2 Rails Developer. Partime hoặc Fulltime.

### ISSUE THREAD

**Issue by trongvominh** [ruby-vietnam/job_board#37]
Hello Ruby VN. Hiện mình cần 2 devs có kinh nghiệm Rails tối thiểu 1 năm kinh nghiệm, ít nhất có kinh nghiệm 1 dự án. Start vào đầu tháng 3/2015. Công ty ở Q1 Sài Gòn.

Partime hoặc fulltime ok. Dự án Nhật.

Thông tin dự án: Ruby on Rails 4, PostgreSQL, Git, Bootstrap HTML5/CSS3. Centos Linux Server, team 8 người.

Contact: trongvominh @ gmail . com
(DT: 093 888 32 hai ba)

**Comment by Gnouc** [comment]
Có tuyển remote không bạn?

**Comment by trongvominh** [comment]
Yeap. bên mình có tuyển remove.

On Tue, Feb 17, 2015 at 3:38 PM, Cuong Manh Le <notifications@github.com>
wrote:

> Có tuyển remote không bạn?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ruby-vietnam/job_board/issues/37#issuecomment-74633741>
> .
>



-- 
*Vo Minh Trong *
Senior Software Developer ( PHP / Perl / Front-End / Responsive Web)
Tel:  +84 093.888.3223 - Skype: trongvominh
Location: Ho Chi Minh City

**Comment by trongvominh** [comment]
Bên mình có tuyển remote bạn nhé.

On Wed, Feb 18, 2015 at 12:28 PM, Trong Vo Minh <trongvominh@gmail.com>
wrote:

> Yeap. bên mình có tuyển remove.
>
> On Tue, Feb 17, 2015 at 3:38 PM, Cuong Manh Le <notifications@github.com>
> wrote:
>
>> Có tuyển remote không bạn?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/ruby-vietnam/job_board/issues/37#issuecomment-74633741>
>> .
>>
>
>
>
> --
> *Vo Minh Trong *
> Senior Software Developer ( PHP / Perl / Front-End / Responsive Web)
> Tel:  +84 093.888.3223 - Skype: trongvominh
> Location: Ho Chi Minh City
>



-- 
*Vo Minh Trong *
Senior Software Developer ( PHP / Perl / Front-End / Responsive Web)
Tel:  +84 093.888.3223 - Skype: trongvominh
Location: Ho Chi Minh City

**Comment by Gnouc** [comment]
@trongvominh Em đã gửi Resume vào mail của anh, không biết anh đã check chưa ạ?

**Comment by trongvominh** [comment]
Hello,

Bạn gởi lại lần nữa được ko, mình chưa thấy CV attachment của bạn.

2015-02-24 11:39 GMT+07:00 Cuong Manh Le <notifications@github.com>:

> @trongvominh <https://github.com/trongvominh> Em đã gửi Resume vào mail
> của anh, không biết anh đã check chưa ạ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ruby-vietnam/job_board/issues/37#issuecomment-75698479>
> .
>



-- 
*Vo Minh Trong *
Senior Software Developer ( PHP / Perl / Front-End / Responsive Web)
Tel:  +84 093.888.3223 - Skype: trongvominh
Location: Ho Chi Minh City

**Comment by Gnouc** [comment]
@trongvominh Em đã gửi lại rồi anh nhé, anh check mail giúp em. Em cảm ơn.

**Comment by trongvominh** [comment]
Dear Cuong Manh Le.

Hiện dự án đang cần người Full Time. Bạn có thể ok full time dev RoR không ?

Thanks.
Trọng

On Wed, Feb 25, 2015 at 10:57 AM, Cuong Manh Le <notifications@github.com>
wrote:

> @trongvominh <https://github.com/trongvominh> Em đã gửi lại rồi anh nhé,
> anh check mail giúp em. Em cảm ơn.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ruby-vietnam/job_board/issues/37#issuecomment-75901675>
> .
>



-- 
*Vo Minh Trong *
Senior Software Developer ( PHP / Perl / Front-End / Responsive Web)
Tel:  +84 093.888.3223 - Skype: trongvominh
Location: Ho Chi Minh City

**Comment by Gnouc** [comment]
@trongvominh Hi anh, em ở Hà Nội nên chỉ có thể làm remote thôi, còn Part time hay Full time đều được.

**Comment by trongvominh** [comment]
Hello, cho mình số điện thoại của bạn với.

On Tue, Mar 10, 2015 at 5:06 PM, Cuong Manh Le <notifications@github.com>
wrote:

> @trongvominh <https://github.com/trongvominh> Hi anh, em ở Hà Nội nên chỉ
> có thể làm remote thôi, còn Part time hay Full time đều được.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ruby-vietnam/job_board/issues/37#issuecomment-78025242>
> .
>



-- 
*Vo Minh Trong *
Senior Software Developer ( PHP / Perl / Front-End / Responsive Web)
Tel:  +84 093.888.3223 - Skype: trongvominh
Location: Ho Chi Minh City

**Comment by Gnouc** [comment]
@trongvominh Hi anh, số điện thoại của em: 0934611090

**Comment by joneslee85** [comment]
@Gnouc @trongvominh xin trao đổi thông tin cá nhân thông qua email

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
