### ISSUE TITLE
doindie Music website  - Rails lead developer p/t

### ISSUE THREAD

**Issue by rydemods** [ruby-vietnam/job_board#38]
We are looking for a new lead RoR developer to take over and complete a update to doindie.co.kr 
( development version here: http://doindie.swdstage.com:3000/  ) 
we are about 75% complete on recent update until our current developer has fallen sick with Dengue! 
so we must find a new developer to carry on his task and make some new improvements and debug a few basic errors.
This project would be ideal if some one is looking to work over the TET holiday or even after as a part time job, we think there is about 2 weeks full time work ( around 100 hours max)  to complete this project this time we have added extra to give new developer chance to catch up and work out the system from the code on github. 
we have integrated a magento shop into the rails app with api - our magento developer in Saigon will be available  to talk to you if need to, but most of the work is to fix rails issues and deploy and maintain as a part time on going project if you wish. 
Top Level of pay available for right candidate willing to pay in person in cash.

## Location

* Siagon, Vietnam   
* Remote

## Requirements
* RoR  senior experienced! 
* PostgrSQL

### Must Have

* High attention to detail is a must
* communicate via email / chat in English well
* show examples of code in rails and or app deployed for a membership type app

### Ideally

* Some knowledge of Korean would be a bonus - but not necessary ( site is in english too) 

### You’ll be responsible for

* completing task in rails app to update some basic functionality 
* deploying to test and live servers
* Checking with Magento developer in Saigon about mage API integration 

### You can bring

* A good eyes for font end
* desire for latest web standards and trends
* passionate to improve the website functions share ideas.

### Contact

stevie@seoulwebdesign.com  
skype:  stevie.dean
phone: +82-10-2252-3193

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
