### ISSUE TITLE
TwentyCI UK - Ruby Technical Leader

### ISSUE THREAD

**Issue by laptrinhcomvn** [ruby-vietnam/job_board#39]
## Hanoi

* Hanoi, Vietnam
* Remote

## Requirements
* Ruby is must
* MySQL
* 1+ years Software Engineering experience

### Must Have

* Solve problems with Ruby
* Handle Ruby projects for company
* Good English

### Ideally

* Experience with 

### Responsibilities

Great power comes with great responsibilities!

### You’ll be responsible for

* Building internal project for company.

### Contact

tung.le@gsmartsolutions.com (0936828488)

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md

**Comment by laptrinhcomvn** [comment]
Hi,

Please remove this job.
I will request add new after few weeks later.

Thank you for your support board :)

Thanks & Best Regards,

--
Le Anh Tung
tung@laptrinh.com.vn
(+84).936.82.84.88
(+84).1646.77.3333
