### ISSUE TITLE
ZIGExN VeNtura Co., LTD - Web Developer

### ISSUE THREAD

**Issue by ltmv** [ruby-vietnam/job_board#4]
## Location

* Ho Chi Minh, Vietnam

## Requirements

* Graduated from College/ University specialized in Information Technology
* 2+ years Software Engineering experience
* Familiar with PHP/Java/Ruby programing languages
* Familiar with Javascript/HTML/CSS
* Familiar with OOP methodology
* Experienced in Web services protocol such as HTTP, REST, SOAP
* Experienced in MVC framework (Symfony, CodeIgniter, CakePHP, Zend, Struts, Spring, Hibernate, Ruby on Rails)
* Familiar with Database design (MySQL, PostgreSQL, NoSQL DB)

## Skills

* Good at English is a huge plus
* Knowing Japanese is definitely a plus 

### Must Have

* Can-do attitude

### Ideally

* Have experience working with Linux system (Centos, Ubuntu)
* Have basic knowledge about software testing
* Have experience working with version control system such as SVN, Git
* Have experience in key-value store engine (Redis), back-end index engines such as Sphinx, Solr is a huge plus

### You’ll be responsible for

* Analyze system requirements/specification
* Design, develop and test web application
* Coordinate with Project Manager and Bridge SE to resolve issues
* Write technical documentation
* Support team members to resolve technical issues 

### Contact

Ms. Yen Pham: g-hr_at_zigexn_dot_vn (0902.959.785)
ZIGExN VeNtura Co., LTD
Add: 17 No.2 street, ward 4, dist. 3, HCMC, Vietnam

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
