### ISSUE TITLE
Employment Hero - RoR Developer

### ISSUE THREAD

**Issue by MQuy** [ruby-vietnam/job_board#41]
### Location
Ho Chi Minh, Viet Nam

### Who we are?
We are looking for talented developers to join the team.
Our team is a small group of passionate individuals that love what we do and be willing to help ones who begins or wants to start his adventure with Rails.
If interested, please reach out to me via email. We will be glad to welcome you in our team!
(or you know someone that fits the position, please let them know. Thanks in advance)

### Contact
Email: tien.le@employmentinnovations.com

**Comment by longkt90** [comment]
wow :) should add your high salary range, and benefits also. FYI contact not contract :v:

**Comment by MQuy** [comment]
haha, it's negotiating salary :neckbeard:

**Comment by anduong** [comment]
But can you give the range @MQuy ?

**Comment by MQuy** [comment]
I think it's about 1000$ -> 4000$

**Comment by anduong** [comment]
@MQuy thanks!

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
