### ISSUE TITLE
JobReady - Front End Developer

### ISSUE THREAD

**Issue by rauxalach** [ruby-vietnam/job_board#43]
## Location
Remote
## Job Ready
Hello, we are JobReady, the leading software provider for the VET and Unemployment
Services industry in Australia. We are looking for a talented Front End Developer to join our
ever growing team.

## Who are you?

* You are passionate about front end development and want to apply your skills working on
projects that truly make a difference.
* In this role you will be leading the charge of building rich user interface components for use
across the JobReady suite. You will be tasked with creating web components, html and css
that display innovative, engaging user centered design.
* You will be responsible for the overall implementation HTML and CSS for JobReady’s
product suite. The Front End Developer works closely with Product and Engineering Teams
on delivering consistent, user friendly, unique applications meeting the overall objectives of
the organisation.

## You will be

* A full stack developer with a strong experience on HTML5, Javascript, CSS.
* Ability to lean new language and solve complex business problems
* Experience in Agile and Scrum development methodologies
* Experience in Test Driven Development and continuous integration
* Team player who collaborates and incorporates feedback from all relevant
stakeholders.
* Knowledge of server side design patterns and continuous delivery principles
* Ability to work independently with minimal direction

## You should have

* Superior skills in applications including, Adobe Creative Suite (Photoshop, Illustrator,
InDesign, and Acrobat) and Microsoft Office.
* Excellent organisational, communication and interpersonal skills because we like that
at JobReady.
* Proven knowledge of modern front-end development approaches including HTML5,
CSS
* Be proficient with advanced Javascript concepts; React.JS, services, promises and
Javascript design patterns, callbacks, classes

### Contact

Huy Le: lvthuy_at_gmail_dot_com (0908.108.625) for more information.

Thanks.

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
