### ISSUE TITLE
LHV Software - Ruby on Rails developer

### ISSUE THREAD

**Issue by chungphuoc** [ruby-vietnam/job_board#44]
## Location
76 Cach Mang Thang Tam, Phuong 6, Quan 3, TP HCM

## Salary
Negotiate

## Description
Develop & maintain software systems & web applications.
 
Read & understand technical specifications, analyze product requirements, design features, implement & test software components.
 
Responsible for troubleshooting application related issues and insuring/maintaining high performance and browser compatibility.
 
Develop internal & appropriate external documentation content.
 
Ensure conformity of work to software quality standards.
 
Provide assistance to Support Engineers with customer support tasks.
 
Benefits:
 
- 13th salary is paid before Lunar New Year.
- Support English and IT courses.
- Support sport cost for employee (badminton, football, swimming, etc.)
- Support team building activities including: a company dinner once a month; 1-day company excursion (on Saturday or Sunday) per month; 3-day company tour once a year.
- Good health care & insurance programs.
- Extra leaves & holiday.
- And other good benefits

## Requirements
General:
 
- Years of experience: 2 year(s)
 
- Minimum career level: Experienced (Non-Manager)
 
- Excellent logical thinking ability.
 
- Ability to work in a team.
 
- Ability to work under pressure.
 
- Excellent knowledge of OOP.
 
- Good problem solving, collaboration, and communication skills.
 
------------
 
## Skills
 
- Experience with Ruby on Rails
 
- MySQL5
 
- Must knowledge MVC model
 
- Experience of web development. UI and usability understanding.
 
Additional software skills are a plus:
 
- HTML5
 
- NoSQL Databases, Hadoop
 
- NodeJS, jQuery
 
- Professional knowledge of JavaScript / Jquery/Ajax, CSS, HTML, CMS.
 
- Some Systems Administration or DBA experience.
 
- Some Exposure to Mobile Development
 
- Some Exposure to Java Applications
 
- Ability to work on both UNIX and Windows platforms.
 
- English skills in reading and writing.
 
- Experience with geographically distributed development teams is a strong plus.
 
- Experience with version control systems, SVN preferred

### Responsibilities

Develop web applications in Ruby on Rails, PHP, Javascript, and related technologies.
 
Read & understand technical specifications, analyze product requirements, design features, implement & test software components.
 
Responsible for troubleshooting application related issues and maintaining application performance.
 
Develop internal & appropriate external documentation content.
 
Ensure conformity of work to software quality standards.
 
Learn new technologies as required for new projects.

## Contact

Email: ohcphuoc@lhv.vn

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
