### ISSUE TITLE
[AsianTech Đà Nẵng] Ruby on Rails developers 

### ISSUE THREAD

**Issue by rockkhuya** [ruby-vietnam/job_board#47]
Công ty mình cần tuyển không giới hạn developers về Rails. Yêu cầu là có niềm đam mê và tinh thần học hỏi. Nếu có kinh nghiệm thì càng tốt. 

Một chút về công ty : Công ty ở tầng 7, toà nhà Indochina, Đà Nẵng. Cty mới thành lập 1 năm, nhưng hiện tại đã phát triển lên đến 120 người. Cty chuyên nhận các dự án từ Nhật về. Vì thế nếu bạn biết cả tiếng Nhật thì đó là 1 lợi thế vô cùng lớn :D. 

Mọi liên hệ các bạn gửi về địa chỉ mail rock.khuya@gmail.com để biết thêm chi tiết :).

**Comment by rockkhuya** [comment]
Một vài thông tin bổ xung : 

 Working days: MONDAY to FRIDAY
- Annual company trip.
- Annual health check 
- Lunch Meal.
- 13th month salary bonus ( maybe 14th month salary bonus)
- Public holidays Bonus
- Review to increase periodic salary annually.
- Joining Company Sports Club: Football, billard,…  
- Participate in employee motivational activities - team building ( monthly, yearly)
- Recruitment bonus 
- English/Japanese classes 
- Other benefits: according to Vietnam Labor Law.

Ngoài những điều này ra, mình nghĩ quan trọng nhất là tầm nhìn và định hướng của công ty. 
AsianTech mới thành lập được 1 năm nhưng hiện đã lên tới 200 người, mọi quy định hay định hướng của cty đều theo quan điểm là đảm bảo quyền lợi cho anh em và tạo ra không khí làm việc hạnh phúc nhất có thể :). 

Đà Nẵng là thành phố đáng sống nhất Việt Nam, còn AsianTech quyết tâm trở thành công ty đáng làm việc nhất Việt Nam :). 

Hi vọng sớm nhận được CV của các bạn :).

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md

**Comment by nguoitapsu12** [comment]
Chào anh. Hiện giờ công ty có còn tuyển dụng không vậy.

**Comment by joneslee85** [comment]
@nguoitapsu12 bạn liên hệ qua email nhé

**Comment by a8thunder** [comment]
Bên mình có tuyển frontent reactjs/redux không a:)))

**Comment by HieuCR7** [comment]
chào anh! hiện tại công ty còn tuyển tuby nữa không anh

**Comment by huatam391** [comment]
Chào anh, không biết công ty bên anh có tuyển fresher RoR ko ạ?
