### ISSUE TITLE
Tech in Asia - Senior Ruby on Rails developer

### ISSUE THREAD

**Issue by vumanhcuongit** [ruby-vietnam/job_board#48]
![tech-in-asia_logo_big1](https://cloud.githubusercontent.com/assets/2767287/6839609/ccdc408c-d39d-11e4-87a6-bfcbfe63bda2.png)

Our Ruby on Rails engineer will be in charge of developing features for [Techlist](http://techlist.asia), a premium database for the Asian startup scene. You should be comfortable both with working on the command line as well as crafting fluid user experience interfaces. You should be able to make judgement calls on product and development decisions, yet feel right at home having to perform a deep dive into any debugging issue.

You will be working closely alongside similarly-talented and self-driven team members who are looking to make an impact on the tech scene in Asia.

**Requirements:**

 * 3+ year of experience with Rails or at least 1 year experience in Rails and 2 years in Web Development
 * Strong frontend skills with HTML/CSS and jQuery
 * Knowing Angular.js and Bootstrap is a plus
 * Experienced with TDD approach, OO design and design patterns
 * Proactive in communication
 * Passionate with programming and exploring technology trends
 * Open­-minded and willing to work in startup scene

**Benefits:**

 * Work in extensively ­using English using environments
 * Receive regular training about work and communications
 * Chance to work onsite or visit our offices across 5 countries

**Salary:** $900+

If you are interested in this job, please send your CV (written in English) to
justin@techinasia.com or ruby@techinasia.com

Office address: B2001, 328 Vo Van Kiet, Dist 1, HCMC

Working time: 9:30 AM ­ 6:30 PM

**Comment by joneslee85** [comment]
Great job post, love the details you put in :+1:

**Comment by joneslee85** [comment]
congrats, it seems to me you have what you are looking for

**Comment by rebyn** [comment]
Highly doubt it. Seems to me the recruitment scene in HCMC is quite gloomy at the moment.

**Comment by joneslee85** [comment]
@rebyn I would not use the word gloomy to describe it, it's just that the right people are not on the market. And Vietnam is not alone, the same thing here in Australia, good talents are elusive, as it has been.
