### ISSUE TITLE
Hiworld.jsc recruitment - Senior Ruby on Rails Engineer

### ISSUE THREAD

**Issue by hainq** [ruby-vietnam/job_board#49]
Title: Hiworld tuyển Senior Ruby Engineer
Content:
 Hiện tại, hiworld đang hợp tác với ventures trong đại học Tokyo (Todai) để triển khai các bài toán về big-data, natural language processing, japanese text processing, machine learning.  
## Location

• 3F, Hoang Ngoc Building, 72 Trần Thái Tông, Cầu Giấy,  Hanoi, Vietnam

## Requirements
* Ruby
* frameworks: rails 
* MySQL/moongra
* 3+ years Software Engineering experience

## Skills
• Có kinh dựng team và lead team về mặt kỹ thuật 
• Có kinh nghiệm triển khai dự án độc lập (dựng môi trường, deploy, xử lý các vấn đề trong dự án) 
### Salary: từ 600$ trở lên, tùy theo kinh nghiệm. 

Contact
Ms Huyền: hr@hiworld.com.vn hoặc 04 626 91 686

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
