### ISSUE TITLE
Steven - Rails developer - music site eCommerce (contractor)

### ISSUE THREAD

**Issue by rydemods** [ruby-vietnam/job_board#5]
Chúng tôi đang cần một lập trình viên Ruby On Rail có kinh nghiệm để tham gia một dự án ngắn hạn. Thời gian khoảng 1 tháng hoặc hơn. Dự án của chúng tôi cần tương tác với hệ thống của Magento thông qua API củ thể dùng giao thúc SOAP.
Chúng tôi đang cần một lập trình viên Ruby On Rail có kinh nghiệm để tham gia một dự án ngắn hạn. Thời gian khoảng 1 tháng hoặc hơn. Dự án của chúng tôi cần tương tác với hệ thống của Magento thông qua API của magento.

Stevie@seoulwebdesign.com

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
