### ISSUE TITLE
[HCM] DWORK - Mid-level Ruby on Rails developers wanted! ($500 - $800)

### ISSUE THREAD

**Issue by tieubao** [ruby-vietnam/job_board#51]
Chào mọi người, team **[DWORK](http://dwork.vn)** (vừa mới nhận đầu tư được 1 tháng) đang làm việc cùng đối tác Hàn Quốc, cần chiêu mộ thêm 2 bạn Ruby on Rails để chuẩn bị cho các dự án tiếp theo.

Team hiện tại đang có 3 thành viên, và có kế hoạch mở rộng lên 15 thành viên vào cuối năm nay. Tham gia DWORK vào thời gian này bạn sẽ nắm chắc trong tay cơ hội làm leader của một nhóm startup trẻ và thỏa sức sáng tạo trong công việc của mình.

## Prerequisite
- Always want to improve yourself
- Want to do something in your way
- Love to work in a startup, flat team with extremely effective collaboration
- High responsibility & confidence
- Able to work in a team with other members.
- At least 1 year or 1 done project in experience.
- Convention
- Everything is architecture
- Know how to use Git.
- Watching trends and best practices in development.
- Reading blogs and compiling ideas how to improve our skills.
- Know how to handle the entire software development life cycle, end to end is a plus.

## Requirements

- Grokking into one framework: Rails or Lotus
- Hardcore developer with a strong experience on HTML5, Javascript, CSS.
- Be proficient with advanced Javascript concepts; Angular or React.JS, services, promises and Javascript design patterns, callbacks, classes.
- Ability to learn new language and solve complex business problems.
- Experience in Agile and Scrum development methodologies.
- Team player who collaborates and incorporates feedback from all relevant stakeholders.

Mọi thông tin liên lạc các bạn có thể tìm thấy tại: http://dwork.vn/jobs/web-developer

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
