### ISSUE TITLE
[HCM] Vinova - Ruby on Rails developer wanted!

### ISSUE THREAD

**Issue by jonathan-vinova** [ruby-vietnam/job_board#52]
## Vinova - Ruby on Rails developer
We, the Vibrant Innovators, earn respect from customers for being committed to quality, flexibility and speed. We strike to build killing products by working closely with customer, by working passionately, and by collaborating openly and disciplinary. 
You will be working in an encouraging and challenging environment, taking advantages of the latest technology to develop excellent apps for clients. 
If you are ready, we welcome you to come and join Vinova team in the mission of making utmost satisfaction for customers.
If you are still wonder who we are, simply Google "Mobile Developer Singapore". Our name is among the tops of the list.
Website: www.vinova.sg
Facebook: https://www.facebook.com/vinova.sg
Email: hr.hcm@vinova.sg

## The Job
* Do you really want to create awesome world-class Apps for customers using latest technologies?
* Do you really want an agile, encouraging and challenging environment for your to master your programming skills?
* Do you really want to work with well-rounded and discipline teammates?

## Responsibilities
* Be extraordinary.
* Be creative.
* Be humble.
* Build real products for many different markets with lots of exciting challenges. 
* Analyze and understand project’s requirements from clients.
* Participate into the development: Design, code and testing the functions or system.

## Requirements
* HTML 5/CSS 3/SASS/Jquery/Ajax
* Javascript/CoffeScript
* Experienced working with Linux system
* Experienced with web service protocols such as HTTP, REST, SOAP.
* Relational and Non-Relational Database
* Experienced deploy system on Heroku/Amazon EC2 
* Experience in Testing, Test Driven Development and Pair programming.

## Skills
1. Have a strong background in IT (general knowledge about algorithm, data structure, programing 
principle, database, operating system is an great advantage).
2. Understand object oriented programming principle, get familiar with some OOP languages.
4. Able to work on any aspect of development.
5. Worked well in team and individually upon request.
6. Able to read/write well in English.

## WHY YOU’LL LOVE WORKING HERE
We have a fun, Silicon Valley style startup culture that values openness, fun and awesomeness.
We offer:
* Chance to become leader of a startup team.
* A fun, awesome work environment.
* Progressive and international working environment.
* Competitive salary plan with benefits
* Provide Macbook for work.
* Exciting company activities.
* Attractive salary and annual salary review.

### Contact
Do not hesitate to contact us at hr.hcm@vinova.sg, or follow us on Facebook. Please attach your CV and portfolio with any works that you have done and impress us.

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
