### ISSUE TITLE
IT services and specifically with Ruby on Rails

### ISSUE THREAD

**Issue by trungcanthi1** [ruby-vietnam/job_board#54]
Singapore firm need IT outsoucing company at HCM 

Look for IT company that provides IT services but specifically with Ruby on Rails

## HoChiMinh city

* Vietnam
* Remote

## Requirements 
IT services and support for Ruby on rails

### Contact

Mr. Trung :  tientrungpham79@gmail.com, will discuss about details after getting contact via email, thanks

**Comment by joneslee85** [comment]
@trungcanthi1 Thanks for the post, however this job board is not designed for Business to Business. We only allow job post that seeks developers. Please post a new one with more details on the job and the skillset you are seeking.
