### ISSUE TITLE
ITviec -- 1 RoR Team Lead and 1 RoR Full Stack Dev

### ISSUE THREAD

**Issue by harveyc99** [ruby-vietnam/job_board#55]
Do you love to build awesome products in Ruby on Rails?

Are you a front-end, back-end, architect kind of guy or gal? Love product? Do you train your cat using Agile methods? 

If so, ITviec.com has a job for you!  Our mission is to help IT people in Vietnam grow their careers, build cool stuff and maybe -- just maybe -- change the world.

Location: Ho Chi Minh City, Binh Thanh 

Skills:
- Several years experience developing in Ruby on Rails
- PostgreSQL
- Scrum

Experience:
- (Team Lead) -- 3-6 years experience, including as team lead/scrum master
- (Full Stack Developer) -- 1-4 years experience

You'll be responsible for:
- Supporting our product vision through technical excellence as we work to become the coolest jobs website in Asia. 
- (Team Lead) Leading the team, dividing responsibilities, planning technical evolution of site, ensuring our code is clean and efficient

We offer our people: 
- A fun, friendly place to work 
- Continuous soft skill training and career coaching 
- Great working hours -- 8:30 to 5:30 (we believe that 8 hours per day is plenty when you're focused on the right things)

If you want to learn, if you have fire in your heart and hunger in your eyes, if you want to make a difference in IT in Vietnam -- then ITviec may be for you.

Want to learn more? Contact me today! -- chris@itviec.com

**Comment by harveyc99** [comment]
Did I mention we have awesome benefits? Check us out today!

**Comment by longkt90** [comment]
Typing mistake, PostgreSQL not PostgrSQL :D

**Comment by harveyc99** [comment]
Thanks

On Sun, Apr 12, 2015 at 6:25 PM, Long Nguyen <notifications@github.com>
wrote:

> Typing mistake, PostgreSQL not PostgrSQL :D
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ruby-vietnam/job_board/issues/55#issuecomment-92038485>
> .
>



-- 
<https://twitter.com/#%21/chrisfharvey>Twitter: @chrisfharvey
<http://www.twitter.com/chrisfharvey>
Website: http://www.chrisfharvey.com

**Comment by rauxalach** [comment]
:+1:

**Comment by handleror** [comment]
:+1:

**Comment by huynhquancam** [comment]
:heart:

**Comment by baothi** [comment]
:+1:

**Comment by duykhoa** [comment]
:heart: :green_heart: :yellow_heart: :blue_heart: :purple_heart:
