### ISSUE TITLE
Fulltime Ruby on Rails Developer - ~1000$ Salary

### ISSUE THREAD

**Issue by thaihajp** [ruby-vietnam/job_board#56]
## Location

* TP HCM, VietNam

## Requirements
* Ruby
* Rails Framework
* MySQL
* 3+ years Ruby on Rails experience

## Skills
* Working with Git, Github
* SCSS/HAML/CoffeeScript
* MySQL
* Redis
* Rails 4, Ruby 2
* Clean code

### You’ll be responsible for

* Building main features for website

### Contact
Hoai An: anvh@kiwisoftware-international.com

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
