### ISSUE TITLE
Mortgage Club - Top Talent Fresh Engineer Wanted (salary $1,500 - $2,500/mo, free Macbook & lunch & gym & laundry)

### ISSUE THREAD

**Issue by billytran1222** [ruby-vietnam/job_board#57]
## About us
* Mortgage Club is an early stage fintech startup based in San Francisco. We leverage data and technology to revolutionize the 8 trillion dollar mortgage industry by making it cheaper, faster, and more transparent. We’re building a real-time mortgage marketplace where home buyers can easily apply, shop, and lock in the best loan in minutes.  

## About the job
* We’re looking for 2 smart, creative, and independent engineers to help build our company from the ground up. You’ll help build an user-friendly interface that makes applying for mortgage as simple as booking a flight or hotel. Join us if you want to help homebuyers get in their next home.

## Must have
* Be able to fly (you'll frequently fly to San Francisco to work with the team)
* Be able to drink alcohol (We’re a big fan of work hard play hard culture so expect to have happy hours, team outings, travel several times a year)

## Requirements
* Graduate from a top-tier CS program with 0-3 years of experience
* Experience with Ruby on Rails and/or Javascript (we use React.js for front end and Rails for back end)
* Experience with PostgreSQL
* Comfortable with communication in English

### Location
* Work at Mortgage Club’s Saigon Hacker House in District 1 (coming soon)
* You can live there for free if you’d like. Central location, less than 10 minutes away from cool hangout spots in the city like Bitexco Financial Tower, Vincom Shopping Mall, AB Tower etc.

### Perks
* Free lunch everyday (we always get headache deciding what and where to eat so let’s just do catered lunch)
* Free gym membership (getting fit is good for both your physical appearance and career) 
* Free laundry (you think washing and folding clothes is a good use of your time?)
* Your choice of Macbook Pro or Macbook Air (sorry no Windows)

### Salary
* Competitive salary: $1,500 - $2,500/month (depends on your talent, not experience)
* Potential salary increase of 20-50% after 1 year

If interested, please email your resume to billy@mortgageclub.io. Also send us a cool program that you’ve written in Javascript or Rails. We will conduct a cultural fit interview followed by technical interviews and programming test.

**Comment by joneslee85** [comment]
Do you have any details on this job's stack? What languages does it use for eg?

**Comment by tphbui** [comment]
Hi @joneslee85, as the description states, we are a Reactjs app built on top of a Rails backend. So the languages are mostly javascript and Ruby on Rails. Let us know if you have any other questions.
Thanks.
-Tuan

**Comment by joneslee85** [comment]
@tphbui can you please copy the job description here instead of redirecting users to Google Doc link? Cheers

**Comment by billytran1222** [comment]
@joneslee85: all done, no more external links!:)

**Comment by joneslee85** [comment]
:+1:

**Comment by hiendinhngoc** [comment]
interesting! I like party and I'm good at drinking too :+1:

**Comment by stnguyen** [comment]
I like the "fly frequently part"
Too bad I'm in Hanoi.

Why do you limit to HCMc only when the job is done remotely?

**Comment by billytran1222** [comment]
@stnguyen: we're going to open an office in HCMC soon but I guess it doesn't matter for now. U interested?:)
@hiendinhngoc: then join us hahaa.

**Comment by rauxalach** [comment]
:+1:

**Comment by longkt90** [comment]
:+1:

**Comment by handleror** [comment]
:+1:

**Comment by joneslee85** [comment]
@billytran1222 wish you guys all the best finding the right talents, please close the issue once you found the right people.

**Comment by billytran1222** [comment]
(Y)

**Comment by hiendinhngoc** [comment]
@billytran1222 Unfortunately, I'm not a talent one and having less of experiences.

**Comment by duytd** [comment]
Really interested in the job description :+1:

**Comment by joneslee85** [comment]
@duytd you see, this has proved that if company put much effort in their job description, they will get lots of attention from potential employees. 

@billytran1222 you can make your job post more outstanding by having your company logo on top

**Comment by billytran1222** [comment]
@joneslee85, @duytd: thank you guys. We only got 2 resumes so far. Where's all Vietnamese Ruby talent?

**Comment by joneslee85** [comment]
@billytran1222 please be patient, not all talents are on the market all together.

**Comment by billytran1222** [comment]
:+1:

**Comment by nthngoc277** [comment]
@billytran1222 an impressive job description, very attractive! Unfortunately, I cannot drink alcohol :sob:

**Comment by longkt90** [comment]
:+1:

**Comment by billytran1222** [comment]
@nthngoc277: Hahaa social drinking can be trained. Email me ur resume if u're interested!:)

**Comment by bdthinh** [comment]
:100: IMPRESSSIVEEE
