### ISSUE TITLE
Looking for Experienced Ruby Developer - fulltime in Saigon

### ISSUE THREAD

**Issue by hahoainhi** [ruby-vietnam/job_board#58]
Salary rank
$600 - $800

Job details:
    Having about 2 years experience with Ruby/Ruby on Rails
    Understanding AngularJS
    Experience with NodeJS and MongoDB
    Working with Agile during the projects
    Good at reading/writing in English (communicate in English by email, skype, etc)
If you are interested in this position, please feel free to contact me via nhi.ha-thi-hoai@jobseeker.vn. 
Thank you

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
