### ISSUE TITLE
Saigon - Lixibox - Looking for fulltime front-end developer 

### ISSUE THREAD

**Issue by nguyenquangminh0711** [ruby-vietnam/job_board#60]
## Who are we?
- Young and talented e-commerce start-up aiming to change the whole online cosmetic market.
- A perfect company to enjoy, to learn, to challenge yourself and to grow up.

## Job details
- Develop front-end for the e-commerce website with pixel perfect quality across a variety of desktop and mobile browsers.
- Work directly with the design team and back-end development team to build front-end using HTML/CSS/JavaScript and integrate with the back-end.
- join in the discussion with other teams to optimize UI / UX of the whole website

## Job requirements
- Be able to communicate in verbal English
- Strong experiences with HTML, CSS and jQuery.
- Strong experiences with building responsive websites.
- Able to work with CSS frameworks like Bootstrap
- Able to work with CSS css preprocessor like SASS / SCSS
- Good knowledge of SEO

## Nice to have
- Team-work with Git
- Experiences with HAML template engine
- Experiences with Ruby on Rails

## We offer
- Young and creative working environment.
- Opportunity to join directly to build an e-commerce product.
- Flexible working time.
- Competitive salary: $500 – $1500 based on your talent.

## Company Location
Thao Dien ward – District 2 – Ho Chi Minh City

## Contact
Please send your resume and contact information to **jobs@lixibox.com**

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
