### ISSUE TITLE
CareerLink Vietnam - Front End Developer

### ISSUE THREAD

**Issue by pdtp** [ruby-vietnam/job_board#61]
## About us
We are a new and growing engineering team from CareerLink Vietnam, building the new version of careerlink.vn and other company's products. Currently, we are looking for talented developers to join our team.

## Job details
* Building front-end stack of company’s products.
* Translating UI/UX designs to production-ready JavaScript/CSS.
* Researching new front-end technologies to improve company’s products.

## Skills requirement
* Top-down thinker and problem solving lover, also a strong team player with good English and communication skills.
* Deep knowledge of HTML5, CSS3, jQuery, JavaScript (big plus if you worked or played with CoffeeScript, AngularJS, Node.js before; or you are willing to learn about them).
* Experience with Bootstrap 3, CSS/SASS/LESS.
* Familiar with Git and Linux environment.
* Big plus if you have experience and knowledge in SEO. 

## We offer
* Fun and creative working environment.
* Flexible working time.
* Competitive salary: $500 – $1500 based on your talent.

## Location
Binh Thanh District, Ho Chi Minh City, Vietnam.

## Contact
Please email your resume and github ID (optional) to kazki.matz@careerlink.vn.

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
