### ISSUE TITLE
ZIGExN VeNtura - Ruby on Rails developer wanted!

### ISSUE THREAD

**Issue by jishin** [ruby-vietnam/job_board#63]
## About ZIGExN VeNtura
ZIGExN VeNtura (http://www.zigexn.vn) is an incorporating 100% Japanese-owned company specialized in offshore software development and Internet services. ZIGExN (http://zigexn.co.jp) in Japan is a fast-growing Internet company, has been awarded Japan Technology Fast50 by Delloite in 2011, 2012 and Best place to Work Japan for 4 years in a row.
ZIGExN VeNtura’s visions are:
1. To provide an empowering platform for each individual to maximize their strength and ability
2. To develop and operate innovative Internet services for Vietnamese market
3. To bring innovative Internet services from Vietnam to the world
We’re looking for core members in various important and challenging positions in order to archive the visions.

## Location 
Ho Chi Minh City - Vietnam
A1, Lầu 4, tòa nhà Mirae Business Center, 268 Tô Hiến Thành, P.15, Q.10

## Job Description
- Analyze system requirements/specification
- Design, develop and test web applications in Ruby/Ruby on Rails
- Coordinate with Project Manager and Bridge SE to resolve issues
- Write technical documentation
- Support team members to resolve technical issues

#### Education background
- Graduated from College/ University specialized in Information Technology
- At least 2 years experience as a Web developer

### Technical experiences
- Familiar with **Ruby/Ruby on Rails** framework. **Don't know Ruby, don't worry we will train you :)**
- Familiar with Javascript/HTML/CSS
- Experienced in Web services protocol such as HTTP, REST
- Familiar with Database design (MySQL, PostgreSQL, NoSQL DB)
- Have experience working with Linux system (CentOS, Ubuntu)
- Have basic knowledge about software testing, automation testing (Rspec, Cucumber, Selenium)
- Have experience working with version control system such as SVN, Git
- Have experience in key-value store engine (Redis), back-end index engines such as Sphinx, Solr is a huge plus

###【LANGUAGE SKILLS】
- Good at English (reading/writing/speaking) is a huge plus
- Knowing Japanese is definitely a plus

### How to apply
Send your CV to g-hr@zigexn.vn (Ms. Mai) and we will contact you.
Mobile: 0902-95-97-85

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
