### ISSUE TITLE
CareerLink Vietnam - Full Stack Developer

### ISSUE THREAD

**Issue by pdtp** [ruby-vietnam/job_board#64]
## About us
We are a new and growing team from CareerLink Vietnam, building the new version of careerlink.vn and other company's products. Currently, we are looking for talented developers to join our team.
Technologies we are using:
* Ruby, JRuby, Rails.
* MySQL, MongoDB, Redis, RabbitMQ, and Elasticsearch.
* JavaScript, JQuery, Backbone.js, Sass and CoffeeScript.

## Job details
* Work with other engineers and designers to build and maintain our main products, using latest web technologies.
* Implement and deliver new features for our product improvement.
* Participate in our code review process and improve our engineering practices.

### You should have:
* Strong coding skills and Computer Science fundamentals with knowledge of algorithms, data structure and software design.
* Great problem solving skills and English skills.
* Experience with MySQL and other relational database systems.
* Be able to pick up new languages and new technologies quicly.

### Big plus if you have:
* Work experience with RabbitMQ, MongoDB, and Elasticsearch.
* Experience with building scalable systems.
* Knowledge of UI/UX design.

## We offer
* Fun and creative working environment.
* Opportunity to learn new technology and apply into our products. 
* Flexible working time.
* Competitive salary: $500 – $1500 based on your talent.

## Location
Binh Thanh District, Ho Chi Minh City, Vietnam.

## Contact
Please email your resume and github ID (optional) to kazki.matz@careerlink.vn.

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md

**Comment by pdtp** [comment]
You can delete this post, since it is too old now and we will post new job post in the future.
