### ISSUE TITLE
TOPICA Edtech Group - Rails backend developer

### ISSUE THREAD

**Issue by ethan605** [ruby-vietnam/job_board#65]
## Location

* Hanoi, Vietnam
* On-site

## Requirements
* Ruby
* Rails Framework
* MongoDB
* 1+ years Software Engineering, Ruby on Rails & Object-oriented Programming experience

### Must Have

* Be able to develop Web services using Ruby on Rails (JSON APIs)
* Be able to co-operate with another client-site developers to build online applications.

### Ideally

* Experience with MongoDB, Mongoid, Redis & Sidekiq
* Experience with Debian server configurations, nginx, phusion-passenger

### Responsibilities

* Develop web service to back mobile & AngularJS web clients via JSON APIs
* Support & fix reported issues

### You can bring

* A good mindset of problem analysis & solving skill

### Contact

Thanh Nguyen: thanhnx@topica.edu.vn (Mobile no: +84 166 88 94 995)

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
