### ISSUE TITLE
ITviec - Senior Ruby on Rails Developer $1000-$2000

### ISSUE THREAD

**Issue by harveyc99** [ruby-vietnam/job_board#66]
<b>Do you love to build awesome products in Ruby on Rails?</b>

Are you a front-end, back-end kind of guy or gal? Do you train your cat using Agile methods?

As Senior Developer Ruby on Rails you will help build and scale the coolest and best job website in Vietnam. In doing so you will help IT people in Vietnam grow their careers, build great things and maybe - just maybe - change the world.

Location: Ho Chi Minh City, Binh Thanh

<b>Responsibilities:</b>
- Develop front-end and back-end 
- Participate in weekly scrum meetings in agile environment 
- Translate stories from product owner into product features 
- Look for solutions, not excuses 
- Write automation tests

Also: 
- Be awesome 
- Be creative 
- Be humble 
- See around corners and anticipate problems 
- Make suggestions for our site -- YOU are our user!

<b>Your Skills and Experience</b>

Required: 
- Minimum 2 years experience coding web applications in Ruby on Rails 
- Scrum and sprint experience 
- Demonstrated experience solving coding problems. Tell us a story about a problem you solved. 
- Demonstrated passion and desire to learn and grow your Ruby skill. 
- Good knowledge in UI (HTML, CSS), Jquery/Javascript, coffeescript, sass, html. 
- Have some public projects in github or bitbucket. 
- Comfortable communicating in written and spoken English. 
- Experience with PostgreSQL, Mysql, MongoDB.

Nice to have: 
- Having a blog or giving presentations at Ruby meetups a big plus 
- Experience working on a web product at a product company 
- Full stack experience -- front end, back end, database, designing for scale

<b>Why should you join us?</b>

- A fun, friendly place to work
- Continuous soft skill training and career coaching
- Great working hours -- 8:30 to 5:30 (we believe that 8 hours per day is plenty when you're focused on the right things)
- If you want to learn, if you have fire in your heart and hunger in your eyes, if you want to make a difference in IT in Vietnam -- then ITviec may be for you.

Want to learn more? Contact me today! -- chris@itviec.com
Meet our team! http://blog.itviec.com/about-us/

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
