### ISSUE TITLE
Rubik System [NhaTrang] - Ruby on Rails, Android, iOs developers

### ISSUE THREAD

**Issue by hoasung01** [ruby-vietnam/job_board#67]
*** RUBY ON RAILS
Yêu cầu
- Có 1 năm kinh nghiệm lập trình Ruby, có kiến thức tốt về Database
- Thành thạo HTML/CSS/JavaScrips, jQuery

*** ANDROID:
- Có 1 năm kinh nghiệm lập trình Android.
- Có ứng dụng trên Google Play là 1 lợi thế

*** iOS:
- Có 1 năm kinh nghiệm lập trình iOS.
- Có ứng dụng trên AppStore là 1 lợi thế.

*** Chung:
- Lương khởi điểm từ $300 - $600 (Net Salary)
- Được hưởng đầy đủ các chế độ bảo hiểm theo luật Lao động Việt Nam và theo quy định của công ty
- Được hưởng các chính sách và chế độ khác như:
+ Tham gia các khóa học tiếng Anh được tổ chức tại công ty;
+ Cơ hội đi Singapore nếu tiếng Anh tốt;

Ứng viên quan tâm vui lòng gửi CV hoặc Liên hệ:
Email: huyngvu@gmail.com
Skype: huyngvu
Tel: (+84) 933933839 - (+84) 918811198

**Comment by joneslee85** [comment]
@hoasung01 em tách ra thành 3 job posts nhé

**Comment by taitran2008** [comment]
Job còn không vậy anh ơi ?
