### ISSUE TITLE
eCom Services, Jsc - Ruby on Rails developer [Hanoi]

### ISSUE THREAD

**Issue by nttvank50ftu** [ruby-vietnam/job_board#68]
* Mô tả công việc
-  Thiết lập và phát triển hệ thống quản lý vận hành giao vận toàn quốc, có áp dụng mô hình Agile/Scrum 
-  Thực hiện các giải pháp công nghệ để tối ưu hóa quản lý vận hành
- Xây dựng các công cụ hỗ trợ khách hàng và tích hợp với hệ thống đối tác

* Yêu cầu công việc
- Tốt nghiệp ngành công nghệ thông tin của các trường Đại học Bách Khoa Hà Nội, Đại học Công nghệ - ĐHQGHN và Học viện Bưu Chính Viễn Thông
- Có hơn 1 năm kinh nghiệm làm việc với Ruby on Rails
- Có kiến thức tốt về JavaScript, HTML, CSS
- Có kinh nghiệm làm việc với Linux OS (Ubuntu hoặc Centos), Memcached, Redis, Background Jobs
- Có kiến thức về bảo mật và mạng máy tính 
- Có khả năng đọc hiểu tài liệu tiếng Anh

* Quyền lợi
- Mức lương: 12tr-15tr/tháng
- Tăng lương, hưởng tháng lương thứ 13, thưởng theo quy định của công ty
- BHXH, BHYT, BHTN và các quyền lợi khác theo luật lao động Việt Nam
- Môi trường làm việc sáng tạo, dân chủ, trẻ trung

*. Hồ sơ
- Đơn xin việc
- Sơ yếu lý lịch
- Hộ khẩu, chứng minh nhân dân và giấy khám sức khỏe.
- Bảng tóm tắt quá trình làm viêc
-Các bằng cấp có liên quan

* Liên hệ
Nguyễn Thị Thanh Vân
Email: vanntt@ghtk.vn
Sđt: 0435721077/ 01692792543
Địa chỉ: 175 Cự Lộc, Thanh Xuân, Hà Nội

**Comment by joneslee85** [comment]
@nttvank50ftu xin hỏi là cty bạn tên gì?

**Comment by nttvank50ftu** [comment]
Công ty mình là Công ty Cổ phần Phát Triển Dịch Vụ Thương Mại Điện Tử, eCom
Services, Jsc nhé.
Đăng kí kinh doanh ở Hồ Ba Mẫu, Phương Liên. Hiện tại văn phòng công ty ở
175 Cự Lộc, THanh Xuân.
Cảm ơn bạn

Best regards,

Nguyễn Thị Thanh Vân

Recuitment Dept

eCom Services, Jsc

No.175 Cu Loc Str., Thanh Xuan Dist., Ha Noi

Tel: 043.5721.077

Mobile: 84-1692.792.543

Email: nttvan.k50.ftu@gmail.com

2015-05-29 7:50 GMT+07:00 Trung Lê <notifications@github.com>:

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
