### ISSUE TITLE
Warbler - 2 Senior Ruby Developers

### ISSUE THREAD

**Issue by moball** [ruby-vietnam/job_board#69]
## Location

* Hanoi, Vietnam

## Requirements
* Ruby
* Middleman
* Postgres
* Redis
* Datapimp
* 5+ years Ruby Experiences

### Must Have

* Be able to communicate in English (email & skype)
* Be able to work full time
* Willingness to work at night (from home) 

### You’ll be responsible for

* Building a new & exciting prescriptive marketing platform

### Contact

hung@warbler.com

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
