### ISSUE TITLE
DWork - RoR Developer ($800 - $1200)

### ISSUE THREAD

**Issue by trungnmt** [ruby-vietnam/job_board#70]
## Prerequisite

- We do agile.
- Have experience working in Unix environment.
- Have at least 1 year experience and at least 2 in-production projects
- Convention
- Everything is architecture
- Watching trends and best practices in development.
- Reading blogs and compiling ideas how to improve our skills.
- Know how to handle the entire software development life cycle, end to end is a plus.

## Requirements

- Hardcore Ruby on Rails developer (ActiveModel, role-based authentication, CoC, ActionView, ...)
- Strong HTML, Javascript, CSS experience
- SpreeCommerce experience is a huge plus
- Ability to learn new language and solve complex business problems.
- Experience in Agile and Scrum development methodologies.
- Team player who collaborates and incorporates feedback from all relevant stakeholders.
- Know how to use Git.

## Instruction content
Show us anything that can prove yourself: Github, source code, portfolio, link to your app, resume ... anything.

Email to us at team@dwork.vn with title is [web-developer] Put your name here
And other jobs: http://dwork.vn/jobs

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
