### ISSUE TITLE
DaDaDee - Ruby Developer - Saigon - FT

### ISSUE THREAD

**Issue by huynhquancam** [ruby-vietnam/job_board#72]
## Location

* District 10, HCM, Vietnam.

## Salary expectations

- $800 - $1,200

## Requirements

* Ruby. (1+ years)
* Ruby on Rails. (1+ in-production project)
* HTML / CSS / JS.
* CoffeeScript / SASS.
* Git SCM.
* Linux.

### Must Have

* Good English verbal and written communication skills.
* Good programming skills.
* Be humble, funny.

### Ideally

* Believe in TDD.
* Love to work in product environment.
* Server monitoring experience.

### You'll be responsible for

* Develop front-end and back-end.
* Turn business idea into code.
* Coordinate with company director to resolve issues.
* Participate in daily meeting with product owner.

### What we offer

* Young, friendly team member with open, flexible product environment.
* Great opportunity for career development.
* 13th month of salary.
* Attractive salary that matches your experience and skills.
* Healthcare insurance.

### Contact

Interested in the job? Drop me an email at jack.huang@dadadee.com

**Comment by oItachi** [comment]
up

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md

the title format is not correct

**Comment by huynhquancam** [comment]
Thanks! I have updated the job post as per your request.

**Comment by joneslee85** [comment]
:+1:
