### ISSUE TITLE
PYCOGROUP - Top Talent of Senior Ruby on Rails Developer  (1000$ - 1500$)

### ISSUE THREAD

**Issue by VyDo** [ruby-vietnam/job_board#73]
We are currently searching for a Senior Ruby on Rails Developer with significant experience in Ruby on Rails development backed up with solid general programming experience, exceptional problem-solving abilities, and a strong work ethic. 

You will be a part of a creative team that is responsible for all aspects of the SDLC from the initial specification, through to developing, testing and launching. As a senior developer, you are also expected to provide coaching and mentoring to your team members.
----------------------------------------------------------

RESPONSIBILITIES:
• Working with a dedicated team to develop web applications using Ruby on Rails framework
• Design, build, and maintain efficient, reusable, and reliable Ruby code
• Analyze client requirements to develop functional and technical software requirements
• Develop analysis and design activities based on the SDLC and web development principles
• Help maintain code quality, organization and automation
• Supervise and support other junior developers in fulfilling tasks as well as improving their skills

REQUIREMENTS:
• Education: College or Bachelor of IT-Software or equivalent
• English: Intermediate level or above
• Minimum three years experience with Ruby on Rails, along with other common libraries such as RSpec and Resque
• Strong insight into Ruby syntax and its nuances
• Solid understanding of object-oriented programming
• Able to implement automated testing platforms and unit tests
• Able to integrate multiple data sources and databases into one system. Experience with NoSQL such as MongoDB is a strong plus.
• Proficient in JavaScript and familiar with major JavaScript libraries
• Familiar with SVN and/or GIT
• Familiarity with development aiding tools such as Bower, Bundler, Rake, etc.
• Familiarity with continuous Integration, preferably Bamboo and Sonar
• Ability to work as part of a team, understand the problems of other team members, and when necessary, go above and beyond the job description to work towards a broader team goal

WE OFFER:
Here at the PYCO Group, we don’t just offer you a job, we offer you your future. Here’s your chance to get your hands on…
• The latest technologies for mobile & web development.
• Cutting-edge collaborative software development.
• State-of-the-art mobile financial software development.
• Teammates that challenge you to exceed your limits.
• The finest IT tools to raise your potential to even greater heights.
• The power to deliver some truly awesome products & services.
• A career path that allows you to learn and grow.
• On-the-job English training with a foreign teacher.
• Attractive annual bonuses.
• Private health care program.
• Project Celebration Party

If you interest in our job opportunity, please contact me for more discussion about this job.

Vy Do (Ms.)

Skype ID: crystal_heart_96989 
Email: vy.do@pycogroup.com 
Mobile: 093.383.1991

**Comment by oItachi** [comment]
very cool

**Comment by checkraiser** [comment]
Too much work to do here. I think with that kind of work load, the salary should be > 2k$.
But the most important thing i think here is the stressness of the work. Is the environment and people relaxable to work with ? How about the healthcare for developers ? Is there any entertainment thing beyond coding and computers ?
The job and opportunity here is incredible for all ambitious developers, but i think it needs a little more to persuade talented people.
Best regards.

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
