### ISSUE TITLE
Fame & Partners - Rails Developer [Remote $1200AUD-$2000AUD]

### ISSUE THREAD

**Issue by tobyhede** [ruby-vietnam/job_board#74]
## Location

* Remote (company is based in Sydney, Australia)

## Requirements
* Ruby
* Rails
* Rspec
* Javascript/Coffeescript
* Postgres
* Sidekiq

### Must Have

* Able to communicate in English (slack, github, email,  screenhero & skype)
* Great Ruby and general coding skills 
* Solid front-end html, js & CSS experience
* Minimum of 2-3 years of experience on Ruby on Rails projects 
* git and github (we run everything off PRs)

### Nice to Have

* Experience with Spree Commerce
* Experience on large codebases
* Experience working remotely
* Opinions about how we can constantly improve our code 
* SEO
* react.js

### Responsibilities

You will work directly with the CTO (that's me) and our other engineers in development and ongoing maintenance of our Spree ecommerce platform. We have some interesting work in our pipeline including integration with logistics and manufacturing and fashion analytics.

Our team is distributed with developers in Sydney, Melbourne and Brazil. 

## About Us

Fame & Partners is a vertically integrated, venture funded ecommerce business , merging fashion and technology with a real-time, on-demand supply chain that allows us to respond to fashion trends fast and deliver a totally bespoke experience to our customers. 
### Contact

Toby Hede > tobyh_at_fameandpartners_dot_com

**Comment by joneslee85** [comment]
:+1:

**Comment by tobyhede** [comment]
We found someone good. Thanks @joneslee85. A+ would hire again.

**Comment by joneslee85** [comment]
@tobyhede good to hear that, alway welcome to more job posts from you in the future.
