### ISSUE TITLE
Vitalify.asia - Ruby Senior, Leader  - [1500usd  ~ HCM]

### ISSUE THREAD

**Issue by trungbb** [ruby-vietnam/job_board#75]
Location

HCM (vitalify.asia)
Requirements

Ruby
Rails
Postgres,mysql
Skills

+Must Have
Great Ruby and general coding skills
Solid front-end html, js & CSS experience
Minimum of 3+ years of experience on Ruby on Rails projects
At least 4+years Software Engineering experience
+Nice to Have
AngularJS
Responsibilities

You will report to PM/Tech leader

About Us

Please prefer vitalify.asia

Contact

vfa.trungbb@gmail.com

**Comment by joneslee85** [comment]
From @rauxalach

```
Ruby : 3+ years Software Engineering experience
này có nghĩa gì vậy @trungbb
+3 yrs exp in Ruby hay exp in Programming?
bạn thêm chi tiết về công ty nữa nhé
thông tin bạn cung cấp mơ hồ quá
ruby-vietnam/job_board#74 bạn tham khảo ở đây
job post ko theo đúng format sẽ bị remove ra á
```

**Comment by joneslee85** [comment]
No updation/reply, marked invalid and closed
