### ISSUE TITLE
KodeQ - Angular Senior Developer - HCM (800$ - 1200$)

### ISSUE THREAD

**Issue by trankimhieu** [ruby-vietnam/job_board#78]
## Who we are

An awesome team, young peoples @ HCM, Vietnam. We have bases in US + VN

## Location

* District 1, HCM, Vietnam

## Requirements
* Javascript
* Angular JS
* 1+ years Angular experience
* We do Scrumban
* Have at least 2 in-production projects
* Have good coding convention
* Watching trends and best practices in development.
* Team player who collaborates and incorporates feedback from all relevant stakeholders.
* Know how to use Git, JIRA + Git flow.

## We can give

* Free snack and soft drink
* Free parking
* Good working environment
* Sharing & coaching culture

## Instruction content

Show us anything that can prove yourself: Github, source code, portfolio, link to your app, resume ... anything.

### Contact
Drop an email: jobs@kodeq.com
Read more: http://blog.kodeq.com/post/120079857483/can-gap-thanh-angularjs

**Comment by trankimhieu** [comment]
@joneslee85 Please help me approve it.

**Comment by joneslee85** [comment]
@trankimhieu it is approved

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
