### ISSUE TITLE
DaDaDee - iOS/Android Developer - Saigon, Vietnam ($800 - $1200)

### ISSUE THREAD

**Issue by huynhquancam** [ruby-vietnam/job_board#79]
## Location

* Gia Phu Building, District 10, Saigon.

## Requirements
* [iOS] iOS development stack ObjectC/Swift + Xcode. (2+ years)
* [Droid] Android development stack Java + Android Studio (2+ years)

### Must Have

* [iOS] Familiar with standard iOS frameworks and concepts, such as Cocoa, Social.framework, InterfaceBuilder, StoryBoard, AutoLayout.
* [Droid] Familiar with Android frameworks and concepts e.g. AndroidSDK, Dalvik, Views.
* Oauth v2.0, RESTful API, Design Patterns.
* Looking for solutions, not excuses.
* Good English verbal and written communication skills.
* Be humble, funny.

### Ideally

* Experienced in Agile/Scrum best practices.
* Love to work in product environment.
* Having apps on Apple Store, Google Play is a plus.

### Responsibility

* Develop mobile apps for our e-commerce portal.
* Turn business idea into code.
* Coordinate with company director to resolve issues.
* Participate in daily meeting with product owner.

### What we offer

* Young, friendly team member with open, flexible product environment.
* Great opportunity for career development, chance to grow yourself as a mobile team leader
* 13th month of salary.
* Salary review twice a year.
* Attractive remuneration package that matches your experience and skills.
* Social/Healthcare insurance.
* Free drinks and snacks.

### Contact

Want to learn more about the job? Drop me an message at jack.huang@dadadee.com (with your resume, Github/Bitbucket link, App Store/Google Play links)

[Are you a Ruby Ninja? If so, we want you now.](https://github.com/ruby-vietnam/job_board/issues/72)

**Comment by huynhquancam** [comment]
@joneslee85 Hi anh Trung, please let me know if I should split this into two ads. Thanks in advance.

**Comment by joneslee85** [comment]
@huynhquancam please do

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md

**Comment by huynhquancam** [comment]
@joneslee85 Thanks for the advice. We've actually stopped hiring this position.
