### ISSUE TITLE
Việt Recruit - [HCM] Senior Ruby on Rails Developer ($800 ~ $1100)

### ISSUE THREAD

**Issue by viet-recruit** [ruby-vietnam/job_board#8]
**[Job Title]**
Senior Ruby on Rails Developer

**[Job Type]**
Full-time

**[Location]**
Ho Chi Minh city, Vietnam (district 7)

**[Employer]**
An IT offshore staffing provider (offices in Australia, Singapore and Vietnam), provides Offshore Staff service, create and develop offshore operations to clients

**[Salary Rank]**
- **$800~ $1100** (Gross)
- We're willing to offer higher salary for perfect match candidates

**[Job Details]**
Develop new features (70% of time), support and maintaining (30%)
A really hard projects with lot of codes. We really need someone who are really work hard and can do attitude (Cross platform, PC & Mobile)
Join a team with other good developers:
- Learn the existing project in order to understand the project and its functionals
- Improve & optimize the code
- Analyze, understand the requirements/scope, and develop new features

If you’re interested in this job, please send your CV to us at: **andy@jobseeker.vn**

Thank you!

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
