### ISSUE TITLE
Uneo - Ruby Web Developer - [HCMC]

### ISSUE THREAD

**Issue by karibuTW** [ruby-vietnam/job_board#80]
## Location

* HCMC, Vietnam
* Remote

## Requirements
* Ruby
* AngularJS
* MySQL
* 5+ years Software Engineering experience
* English or French speaking
* In freelance but will work for several months to a year (Can work from home)

### Ideally

* Love to work with startup
* Be proactive
* Share own ideas

### Responsibilities
* Develop new features on our platform
* Correct bugs
* Manage our server

### Details
Our website is a platform to connect professional with people looking for services and general business (Build a house, arrange a wedding, find a DJ, ...)

We will need to build the following features:
- Notification, digest and subscription feature
- Statistics (Response time, response rate,,...)
- Add comments system with the right to answer
And many others "small features"

Afterwards, if all goes well, we would like to build an advanced social platform.

We will be looking for someone for few months to a year, depending your performance and on the business.
These listed tasks are just the beginning as we will be looking for a longer term developer

### Contact
Please contact me by email (karibu at freedif.org) and provide me your past experience/project and your hour/day/week/month rate (Up to you, we will discuss further)

Thank you

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
