### ISSUE TITLE
VCCloud - Junior Ruby on Rails developer - HaNoi (Fulltime, 400$ - 700$)

### ISSUE THREAD

**Issue by tunglam14** [ruby-vietnam/job_board#82]
## Location

* Ha Noi

## Responsibilities

* Help build and maintain cloud computing system’s web services, Ruby on Rails based applications.
* Work on Ruby RESTful Web Services that are integrated with our main application.
* Write beautiful, well tested code.

## Requirements

Strong knowledge in the following areas is expected:

* Experience working with Ruby on Rails. Experience working with Python, PHP and Nodejs is a credit.
* Experience working with MySQL, NoSQL (Redis, MongoDB, ...), Asynchronous Processing, Git, Third Party Authentication Integration.
* Experience working with Debian/Ubuntu or Unix-like Operating System.
* Demonstrable knowledge of front-end technologies such as JavaScript, HTML, CSS & JQuery.

## Contact

Applicants send Curriculum Vitae via email to lamdt@vccloud.vn

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
