### ISSUE TITLE
Ruby On Rails Developer (UPTO $1500) URGENT!

### ISSUE THREAD

**Issue by Framgia-Vietnam** [ruby-vietnam/job_board#84]
MÔ TẢ CÔNG VIỆC:
- Xây dựng các ứng dụng web, webservice
- Tham gia vào thiết kế và review source code
- Báo cáo tiến độ và tình trạng công việc trực tiếp tới quản lý dự án
- Tiếp cận và được đào tạo theo mô hình phát triển dự án Agile, Scrum

YÊU CẦU CÔNG VIỆC:
- Tốt nghiệp đại học, cao đẳng chuyên ngành IT
- Có kinh nghiệm làm việc với Framework Ruby on Rails hoặc các framework khác sử dụng ngôn ngữ Ruby
- Thao tác tốt với HTML, CSS, JavaScript (Jquery, Ajax, ...), Bootstrap, JSON, XML, ...
- Nắm vững về MVC, OOP. Chú trọng performance & refactoring khi viết code
- Có hiểu biết về Design Pattern, ORM, RESTful, TDD, ...
- Có kinh nghiệm làm việc với MySQL hoặc NoSQL (MongoDB, ...)
- Có hiểu biết về Redis, search engine là một lợi thế
- Thành thạo các công cụ quản lý mã nguồn: GIT, SVN.
- Thao tác tốt với các công cụ như NginX, Unicorn, ...
- Có thể làm việc trên môi trường Linux/Ubuntu
- Có khả năng làm việc tốt trong môi trường Teamwork cũng như làm việc độc lập.
- Sử dụng thành thạo tiếng Anh đọc và viết.
- Có thể đảm bảo deadline cũng như chất lượng sản phẩm.
- Khả năng tư duy tốt, chủ động trong công việc, có tinh thần trách nhiệm cao để hoàn thành công việc được giao

CHẾ ĐỘ ĐÃI NGỘ:
- Được hưởng bảo hiểm xã hội, bảo hiểm y tế, bảo hiểm thất nghiệp theo chế độ nhà nước ban hành.
- Lương tháng 13, thực hiện review kết quả công việc, thưởng theo kết quả dự án, xét tăng lương 6 tháng một lần.
- Được hưởng trợ cấp ăn trưa từ 840,000VND/1 tháng (40.000VND/1 ngày làm việc thực tế).
- Trợ cấp Beauty Care 300.000VND/Tháng với nhân viên nữ ký hợp đồng chính thức.
- Trợ cấp đi lại từ 210.000 VND~ 630.000VND/1 tháng (Phụ thuộc vào khoảng cách từ nhà đến Công ty, mức tối thiểu là 10.000VND/1 ngày làm việc thực tế)
- Trợ cấp thai sản (Hưởng thêm 3 tháng lương của nhân viên ngoài lương do Bảo hiểm và nhà nước chi trả)
- Trợ cấp tiếng Nhật, tiếng Anh, và các chứng chỉ IT liên quan (hình thức: khen thưởng, tăng lương...)
- Hỗ trợ phí tham gia Hội thảo ngoài Công ty 100.000 VND/ ngày
- Được tham gia các Câu lạc bộ dưới sự tài trợ chính thức của Công ty: CLB Bóng đá, các CLB Game, CLB dạy và học tiếng Nhật, tham gia các bữa tiệc, hoạt động ngoại khóa của công ty ...
- Du lịch hàng năm.
- Khám sức khỏe định kỳ 1 năm/1 lần tại bệnh viên uy tín.

LƯƠNG VÀ HỢP ĐỒNG LÀM VIỆC:
- Mức lương: $600 – $1500
- Thử việc 2 tháng, lương thỏa thuận
- Thời gian làm việc: Từ thứ 2 đến thứ 6, Self-study: 16h/tháng

CHI TIẾT KHÁC:
- Yêu cầu CV tiếng Anh, ghi rõ về kinh nghiệm làm việc và quá trình học tập của bản thân
- Yêu cầu ghi rõ vị trí tuyển dụng: Ruby Developer

LIÊN HỆ: Để gửi CV ứng tuyển hoặc thắc mắc về thông tin tuyển dụng, vui lòng liên hệ
Ms. Mơ
Email: hr_team@framgia.com
Phone: 0437955417
Web: recruit.framgia.vn

**Comment by joneslee85** [comment]
@Framgia-Vietnam can you please add contact details? thanks

**Comment by hiendinhngoc** [comment]
@Framgia-Vietnam how to apply?

**Comment by Framgia-Vietnam** [comment]
@joneslee85 @hiendinhngoc 
So sorry
Plz send your resume/CV to: hr_team@framgia.com (Ms. Mơ)
Phone: 0437955417
Website: recruit.framgia.vn

**Comment by ytruongdang** [comment]
@Framgia-Vietnam không có bằng đại học cao đẳng có aplly được không?

**Comment by joneslee85** [comment]
@ytruongdang mình không rõ ở nhà nhưng ở nc ngoài nếu có căn bản (tự học)  và đc việc thì không có vấn đề gì cả

**Comment by Framgia-Vietnam** [comment]
@ytruongdang  Framgia VN cũng không yêu cầu phải có bằng đai học bạn nhé. Chỉ cần căn bản tốt và có khả năng đáp ứng công việc là ok.
Bạn gửi CV cho Framgia vào hr_team@framgia.com hoặc add Skype của mình: uocmo1226 trong trường hợp cần hỏi them chi tiết nhé

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
