### ISSUE TITLE
Umbala Labs offers $1500 - $4000 CRAZY senior backend engineers (Ruby, GO, Java, Python)

### ISSUE THREAD

**Issue by tmnguyenus** [ruby-vietnam/job_board#85]
(Saigon, VN) We offer $1500 - $4000/month for 3 CRAZY senior backend developers (Ruby, GO, Java, Python). You can apply via jobs@umbala.co 

Job Desc: http://umbala.tv/careers/category/Umbala-Plaform/Backend-Software-Engineer-(Saigon,-Vietnam)
Page: http://facebook.com/umbalacareers
![mobilehacker](https://cloud.githubusercontent.com/assets/7076459/8648350/304ab9ae-298a-11e5-98e0-e18063716006.png)

**Comment by joneslee85** [comment]
@tmnguyenus I am sorry that the post is not considered a valid post because it's a bit too vague in description. Would you be able to re-submmit separate post? Cheers
