### ISSUE TITLE
Quoine Pte Ltd, Ruby on Rails Developer, Ho Chi Minh ($1000 - $2000)

### ISSUE THREAD

**Issue by chinh7** [ruby-vietnam/job_board#87]
![small](https://cloud.githubusercontent.com/assets/2062919/8899582/750bd664-3460-11e5-88be-ea0964b96919.png)

## Company
Quoine Pte. Ltd. is a fintech company incorporated in Singapore with local partners in Japan. We’re experiencing exponential growth with the latest funding round of $2M. In 9 months, Quoine go from zero to the top Bitcoin trading platform in Japan. Our team is comprised of passionate banking professionals and world-class engineers with extensive experience in financial products. We believe finance is the last sector to disrupt, and Cryptocurrency is the mean to do that. We are looking for top-notch engineers to join our exciting journey and help us build the next generation of Quoine products.

## Location
* Ho Chi Minh, Vietnam
* Fulltime

## Requirement
• Experience shipping production Ruby on Rails app

## Benefits
• Exceptional talent will be matched with exceptional salary ($1000 - $2000)
• An innovative, international working environment with talented colleagues from various countries and backgrounds. 
• Awesome view
• Ping pong, foosball table, treadmill, swimming pool, punching bag, you name it

## You will be an awesome fit for us if 
• You want to be in the next frontier of Cryptocurrency. 
• You want to help build a great company from the ground up. 
• You obsess over software performance and coding excellence. 
• You have the curiosity to explore domains outside your comfort zone. 

## Contact
Please send your CV to chinh [at] quoine.com
(Personal or open source side-project is a big plus)

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
