### ISSUE TITLE
RobustTechHouse Vietnam & Singapore FinTech Foundry - RoR Developer USD1000-2000 Monthly

### ISSUE THREAD

**Issue by mattrobust** [ruby-vietnam/job_board#88]
## About

RobustTechHouse (http://robusttechhouse.com/) is an exciting Singapore and Vietnam based FinTech foundry. We develop FinTech and Ecommerce products in-house. We also work with start-ups and corporations in Asia to build their exciting web & mobile products in Financial (FinTech), ECommerce and Mobile-Commerce sectors. 
We are already re-inventing the FinTech and ECommerce landscape in Asia. 
We need YOU, as our pioneering development extraordinaire and technopreneur, to help us build our robust software and team. You get to work in a great team and join us on our wonderful journey as we build one great thing after another.

* Great Team - You work directly with our excellent, talented and very nice team in Vietnam and Singapore consisting of developers, product managers, financial industry experts and many other cool people.
* Increase Your Value - You get to work on Financial and ECommerce applications and learn about them on the job. We would love to train you on these concepts and increase your knowledge. This will substantially boost your personal skills and value for your future jobs.
* High Visibility - Your opinions & suggestions will be heard and you will help shape the company.
* Equipment – We will provide you the equipment (devices, laptop etc) and good working environment you need to get your job done well. We don’t believe in working on only one monitor either.

## Location

Ho Chi Minh City

## Responsibilities

To work closely with our team in Vietnam and Singapore to design, implement and support our web applications, web front-end, back-end, APIs and many more.

## Skills

* Exceptionally passionate about technology
* Detail-oriented and takes pride in crafting software that is robust and efficient
* Strong interest in Finance, Financial software, ECommerce or very good with numbers
* Technical hands-on development experience in RubyOnRails
* Degree in Computer Science, Information Systems, or a related field
* Full time (40 hours a week)

## Contact

Please send your resume, geek cred (GitHub links, code samples, project portfolio descriptions etc), MD5 hash of the string "RobustTechHouse" to hr@robusttechhouse.com

**Comment by vumanhcuongit** [comment]
Although I no longer work at Robust Tech House (RTH), I still miss this company :). I'm sure that you will have nice colleagues if you join RTH :+1:

**Comment by quocnv** [comment]
:

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
