### ISSUE TITLE
(Junior) Ruby Engineers [$350~$600, Saigon]

### ISSUE THREAD

**Issue by lmkhuyen** [ruby-vietnam/job_board#9]
*Job details:*
Analyze and understand the project’s requirements from clients
Participate into the development: Design, code and testing the functions or system
Follow the working plan and catch up the deadline
Wiling to learn new technologies

*Job requirements:*
1~3 years working on Ruby
Having experience of working with Ruby on Rails
Be able to read and write in English (working environment)
Very good if the candidates can communicate in Japanese

*What we offer to our employees:*
Salary rank: $350 ~ $600 (GROSS)
Offer a long term and stable job
Offer a dynamic working environment where employees chance to develop their career paths
Many other benefits

*How to apply:*
Please send your CV (English) to Le Minh Khuyen (Mr), at khuyen.le-minh @ jobseeker.vn
If you dont see our response after 24 hours, please call us at number (84) 966 728 800
If you have more info about the jobs, or need support, please feel free to drop us a message on Skype khuyencncn

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
