### ISSUE TITLE
KiwiSoft - Ruby on Rails Developer (high salary)

### ISSUE THREAD

**Issue by trongvominh** [ruby-vietnam/job_board#90]
Ruby on Rails Developers
Location: Ho Chi Minh, District 1
Salary: You will like it (Up to 20.000.000vnđ)
Your Skills and Experience
- Graduated from College/ University specialized in Information Technology 
- Very good knowledge in Ruby on Rails and Web Front-end technologies like HTML5, CSS3 
- Have experience working with Linux system (Ubuntu, Centos, Debian ...)
- At least 2 year(s) of working experience in the related field is required for this position.

# Responsibilities: 
- Develop front-end and back-end in Ruby on Rails 4

# Nice to have: 
- Having a blog or giving presentations at Ruby meetups a big plus 
- Experience working on a web product at a product company 
- Full stack experience: Front end, Back end, Database, Designing for scale.

# Why You'll Love Working Here:
We have a fun, style startup culture that values openness, fun and awesomeness.

# We offer our people: 
- A fun, friendly place to work 
- Continuous soft skill training and career coaching 
- Great working hours -- 8:30 to 5:30 (we believe that 8 hours per day is plenty when you're focused on the right things)

Email: trong.vm@kiwisoftware-international.com 
Skype: trongvominh

**Comment by trongvominh** [comment]
[Tuyển dụng tại TP.HCM] Ruby on Rails Developer (high salary)
Tuyển dụng lập trình viên Ruby on Rails ít nhất 1 năm kinh nghiệm.

Địa điểm làm việc: Quận 1, TPHCM. 
Deadline CV: 22/08/2015 
-- Send your CV to email: trong.vm@kiwisoftware-international.com 
-- Contact: skype:trongvominh

**Comment by joneslee85** [comment]
@trongvominh xin bạn cung cấp thêm các thông tin khác của cv, skill yêu cầu là gì, trách nhiệm của vị trí, cty giá trị là gì, vv, mình sẽ không chấp nhận bài post nếu qua vắn tắt và chung chung

**Comment by trongvominh** [comment]
Ruby on Rails Developers
Location: Ho Chi Minh, District 1
Salary: You will like it

Your Skills and Experience:
- Graduated from College/ University specialized in Information Technology 
- Very good knowledge in Ruby on Rails and Web Front-end technologies like HTML5, CSS3 
- Have experience working with Linux system (Ubuntu, Centos, Debian ...)
- At least 2 year(s) of working experience in the related field is required for this position.

Responsibilities: 
- Develop front-end and back-end in Ruby on Rails 4

Nice to have: 
- Having a blog or giving presentations at Ruby meetups a big plus 
- Experience working on a web product at a product company 
- Full stack experience: Front end, Back end, Database, Designing for scale
Why You'll Love Working Here:
We have a fun, style startup culture that values openness, fun and awesomeness.
We offer our people: 
- A fun, friendly place to work 
- Continuous soft skill training and career coaching 
- Great working hours -- 8:30 to 5:30 (we believe that 8 hours per day is plenty when you're focused on the right things)

**Comment by trongvominh** [comment]
@joneslee85 : Yes, Okie. I updated it. Thanks.

**Comment by joneslee85** [comment]
@trongvominh looks great, one more thing, please fix the markdown format for heading, make sure they are bold

**Comment by longkt90** [comment]
:+1:

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
