### ISSUE TITLE
Ruby on Rails Developer - $700 - $1000 Monthly - Remote

### ISSUE THREAD

**Issue by jmarbach** [ruby-vietnam/job_board#91]
#### About Me

I am an American entrepreneur who is building Ruby on Rails web applications that the Chrome browser functionality.

#### Location

Remote 
* We will chat daily over instant messenger and project management software, such as Trello.

#### Job Description

* Analyze system requirements/specification
* Design, develop and test web applications in Ruby/Ruby on Rails
* Write technical documentation

#### Education background

* At least 2 years experience as a Web developer
* Technical experience debugging software applications

#### Job Requirements

* Familiar with Ruby/Ruby on Rails framework
* Familiar with Javascript/HTML/CSS
* Familiar with web protocols such as HTTP, REST
* Familiar with Database design, (MySQL, PostgreSQL, NoSQL DB)
* Have experience working with Linux system, (CentOS, Ubuntu)
* Have basic knowledge about software testing, automation testing, (Rspec, Cucumber, Selenium)
* Have experience working with the Git version control system
* Have experience working with application deployment services, (Heroku) 
* Have experience in key-value store engine, (Redis)

#### Language Skills

* MUST have strong English skills (reading/writing/speaking)

#### Contact

* Find my Gmail email here: http://jmarbach.com/about
* I am looking to get started immediately
* Please include a link to a rails application that you've built

**Comment by quocnv** [comment]
:)

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md

**Comment by jmarbach** [comment]
Please remove this job post.

On Wed, Nov 25, 2015 at 9:15 PM, Trung Lê <notifications@github.com> wrote:

> We've just updated our job post guideline, can you please update this job
> post to comply with it? We will remove this job post after 1 week if no
> changes have been made. Please see new guideline at
> https://github.com/ruby-vietnam/job_board/blob/master/README.md
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ruby-vietnam/job_board/issues/91#issuecomment-159783535>
> .
>



-- 
*John Marbach *| jmarbach.com | 908-256-6465
