### ISSUE TITLE
Fame & Partners - Rails Developer [Remote $2000AUD - $Negotiable]

### ISSUE THREAD

**Issue by tobyhede** [ruby-vietnam/job_board#92]
## Location

* Remote (company is based in Sydney, Australia)

## Requirements
Mid to Senior+ experience
Salary $negotiable based on experience, excellenceness

* Ruby
* Rails
* Rspec
* Javascript/Coffeescript
* Postgres
* Sidekiq

### Must Have

* Able to communicate in English (slack, github, email,  screenhero & skype)
* Great Ruby and general coding skills 
* Solid front-end html, js & CSS experience
* Minimum of 2-3 years of experience on Ruby on Rails projects 
* git and github (we run everything off PRs)

### Nice to Have

* Experience with Spree Commerce
* Experience on large codebases
* Experience working remotely
* Opinions about how we can constantly improve our code 
* SEO
* react.js

### Responsibilities

You will work directly with the CTO (that's me) and our other engineers in development and ongoing maintenance of our Spree ecommerce platform. We have some interesting work in our pipeline including integration with logistics and manufacturing and fashion analytics.

Our team is distributed with developers in Sydney, Melbourne, Ho Chi Minh and Rio de Janeiro. 

## About Us

Fame & Partners is a vertically integrated, venture funded ecommerce business , merging fashion and technology with a real-time, on-demand supply chain that allows us to respond to fashion trends fast and deliver a totally bespoke experience to our customers. 

### Contact

Toby Hede > tobyh_at_fameandpartners_dot_com

**Comment by joneslee85** [comment]
:+1:

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
