### ISSUE TITLE
Lixibox - Fullstack Ruby on Rails Developer

### ISSUE THREAD

**Issue by nguyenquangminh0711** [ruby-vietnam/job_board#95]
![Lixibox logo](https://cloud.githubusercontent.com/assets/11613517/9347490/5c86cb0c-4654-11e5-8429-23ef790797e3.png)
# [Lixibox](https://lixibox.com)

## Who are we?
Lixibox is a young and talented e-commerce start-up funded by well known Silicon Valley investors (Joe Lonsdale of Clarium Capital, Eric Chen of Tiny Prints, Alin Bui of Anduin Transactions etc.). The company aims to change the whole online cosmetic market with creative break-through cosmetic distribution method. Since the beginning, Lixibox keeps growing fast and have a remarkable growth speed comparing to other foreign-based startups in Vietnam. Joining the team, you will have the opportunity to work with young, passionate and talented people in their fields. We follow pure American working style that will make you as comfortable as you want with family culture, flexible working time, beautiful non-traditional office, free drinks (juice, soft drinks even beer if you want), snacks, lunch and a competitive salary. Lixibox is a perfect company to enjoy, to learn, to challenge yourself and to grow up.

## Job details
* We're looking for a full stack Ruby on Rails Developer to join our amazing team to grow an e-commerce website with complicated operations and complex user integrations. 
* Working with operation and marketing team to analyze and optimize the working flow flow of the company.

## Job requirements
* Excellent at Ruby/Ruby on Rails framework
* Have great experience working with Javascript/HTML/CSS
* Have good knowledge about software testing, automation testing (Rspec, Capybara)
* Have experience working with the Git version control system
* Familiar with agile development methodology
* Be able to communicate in English

## Nice to have
* Familiar with working with 3rd-party APIs like Facebook, Sendgrid, Twilio, Slack, etc.
* Familiar to continuous integration testing services like CircleCI 

## We offer
* Young and creative working environment.
* Opportunity to join directly to build an e-commerce product.
* Flexible working time.
* Free snacks, drinks and lunch
* Competitive salary based on your ability and talent.

## Company Location
Thao Dien ward – District 2 – Ho Chi Minh City

## Contact
Please send your resume and contact information to jobs@lixibox.com

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
