### ISSUE TITLE
[HCM] Slife Media - Hybrid mobile developer (Angular Js, laravel, phonegap)

### ISSUE THREAD

**Issue by leovinh** [ruby-vietnam/job_board#97]
We are looking for strong web developers to build Hybrid mobile app.

The skills needed for this position includes:
- PHP, Laravel framework
- Angular JS
- Know PhoneGap/Cordova & Ionic Framework is a plus

Benefit: 400$+
Great working environment (Bay area startup working style) at Saigon Pearl Villa from monday - friday. 
Send CV and github profile to: vinh@slifemedia.com

**Comment by joneslee85** [comment]
@leovinh sorry we do not take PHP job
