### ISSUE TITLE
Fram - Ruby On Rails Developer - [Ho Chi Minh]

### ISSUE THREAD

**Issue by duyva** [ruby-vietnam/job_board#99]
![dsc04177-1-1-1](https://cloud.githubusercontent.com/assets/13993884/9514218/533c2c4e-4cc2-11e5-9750-e761f60c236d.jpg)

# Fram

Fram - the Swedish software Company helps Scandinavian and Northern European companies leverage the talent and power of Vietnamese rock star developers and other online industry talent. Fram is a very different company. First of all, our culture is different – we believe that to write world class code you need to work in an environment that energizes you and with colleagues that inspire and challenge you. Hence, we sit in a special designed, Scandinavian office on Hai Ba Trung in central Ho Chi Minh City. We only work with Scandinavia’s top online employers and we only hire Vietnam’s top 2% developers and internet industry talent. Come and visit us to find out if you have what it takes to become a key player in one of Fram’s great teams.

- Address: Floor 12, TMS Building (172 Hai Ba Trung Str, Dist 1, HCM City, Vietnam)
- Website: http://www.framco.se
- FB: https://www.facebook.com/framco.se

# The Job 

Fram is looking for 02 senior or principal Ruby on rail developers that are writing short code in a specific and structured way. You will be playing a key role in the tech team of a fast growing online educational platform with a global reach.

You have more than 4 years of experience in web development as well as experience in coordinating projects. Very strong English skills in speech and writing are required.
 
Most important is that your coding should be at the highest standard, easily maintainable and easy to read. You are able to work independently, you deliver on time and you take initiative to keep team communication alive at all times.

# Your Skills and Experience

*Requirements*
• Strong Ruby/Rails experience
• Comfortable with agile development, Test Driven Development
• Experience with diversified projects, reference cases (e.g. open source projects)
• Good knowledge in front end coding (CSS/HTML/Javascript/)
• Good sense of code quality
• Team worker
• Long term commitment to the job, willingness to grow with the company
• Strong English in speech and writing

*Nice to have*
• Knowledge/experience with AngularJS
• Knowledge in Coffee Scripts
• Knowledge in HTML5/CSS3

# Why You'll Love Working Here

*More on Fram – what is it like to work in Fram?*
We are passionate individuals driven to succeed. We love the freedom of an entrepreneurial company and are looking for like-minded, ambitious professionals with a desire to build something new and actively support our young company in its growth to greatness.

*You will love working here!*
Fram believes that only the top 2% of the talent pool has what it takes to be part of building world class internet companies. Come and visit us to see what this all means in practice and why Fram is so different. Other things we offer that might interest you are:

• Attractive salary package (1,700-2,500 USD gross)

• Our work culture is characterized by strong team spirit, high degrees of openness and innovation. We have the culture and office of a Scandinavian online company, on Hai Ba Trung in central HCMC.

• Opportunities to improve English skills - English is official language in Fram’s office. You will also gain exposure to interact directly with the client form from day 1, and you will be part of an international team of experts from Vietnam and Scandinavia. Weekly English lessons with professional foreign teachers at Fram’s offices.

• Since Fram is only looking for the top 2%, you will gain the possibility of working with some of the sharpest people in their respective fields, and you will naturally gain hands-on experience with cutting-edge technologies

• Annual leave and insurance policies in compliance with Vietnam’s labor law and company regulations

• 5-day working week (Monday-Friday), working hours to some extent flexible

• Opportunity to become one of the key members of the sharp and hungry team at Fram as we build this fast growing company together!

Do you think you’ve got what it takes? *Apply now!*

# Contact
Duy Vu, Operations Manager • duy.vu@framco.se

**Comment by joneslee85** [comment]
We've just updated our job post guideline, can you please update this job post to comply with it? We will remove this job post after 1 week if no changes have been made. Please see new guideline at https://github.com/ruby-vietnam/job_board/blob/master/README.md
